### ISSUE TITLE
reverting back to same snapshotId causes ganache-core to freeze

### ISSUE THREAD

**Issue by ewingrj** [trufflesuite/ganache-core#104]
## Expected Behavior

I can call `evm_revert` with the same snaphostID multiple times

## Current Behavior

It works correctly the first time, but will cause testrpc to freeze up if reverting to the same id a 2nd time

## Steps to Reproduce (for bugs)

1. create a snapshot
2. rollback to the snapshot you created
3. optionally modify state
4. rollback to the snapshot you created again
5. ganache never returns a response and will not respond to any additional requests

## Your Environment

* Version used: 7.0.0-beta.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version: 
* Operating System and version: osx
* Link to your project:

**Comment by konstantinzolotarev** [comment]
Yep got same bug. 
And also more details on this: 

When you revert any snapshot using `eth_revert` after this you could kill `ganache` using another `evm_rever` with any parameter. Here is "advanced logs"

[Logs in gist](https://gist.github.com/konstantinzolotarev/16b0c339a3cc0a7ba95e3519f1b8018a)

**Comment by davidmurdoch** [comment]
@konstantinzolotarev thanks for providing the additional info. As far as the `evm_snapshot` response change goes, we now (correctly) return an RPC _Quantity_ hex encoded string instead of an RPC _Unformatted Data_ hex encoded string.

**Comment by AlexanderPoschenrieder** [comment]
Still happening v6.2.5.

**Comment by mortimr** [comment]
@tcoulter mentionned that this behavior is intended [here](https://github.com/trufflesuite/ganache-cli/issues/138#issuecomment-241469320)
As snapshots are getting "consummed" after a revert, I just recreate a snapshot after each of my reverts and it's working fine (using this for contract testing)

**Comment by balexander4** [comment]
Documentation has been updated on this to clarify what is occurring. Just awaiting a the PR approval before closing this issue.

**Comment by honestbonsai** [comment]
@ewingrj  Closing as we believe this has been fixed. If that's not the case, feel free to reopen.
