### ISSUE TITLE
Use Check-summed Addresses

### ISSUE THREAD

**Issue by kevinwucodes** [trufflesuite/ganache-core#105]
In Ganache-Core 2.1.0, if you generate accounts with the default mnemonic of **candy maple cake sugar pudding cream honey rich smooth crumble sweet treat**, you get these ethereum accounts:

(0) 0x627306090abab3a6e1400e9345bc60c78a8bef57
(1) 0xf17f52151ebef6c7334fad080c5704d77216b732
(2) 0xc5fdf4076b8f3a5357c5e395ab970b5b54098fef

If EIP-55 is followed, I would expect these ethereum accounts to be:

(0) 0x627306090abaB3A6e1400e9345bC60c78a8BEf57
(1) 0xf17f52151EbEF6C7334FAD080c5704D77216b732
(2) 0xC5fdf4076b8F3A5357c5E395ab970B5B54098Fef

The [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md) reference includes a javascript implementation.

Is there a reason we shouldn't follow EIP-55?

**Comment by sushilbal** [comment]
Currently looking into this issue and hopefully will have a pull request soon. Had a brief discussion with @kevinbluer about this problem and wanted to test the code changes locally before create a pull request. Looking forward to have a deeper discussion with the Ganache team.

**Comment by honestbonsai** [comment]
@kevinwucodes This has been fixed. Closing this issue, feel free to reopen if you still experience issues.
