### ISSUE TITLE
Support WebSockets

### ISSUE THREAD

**Issue by onbjerg** [trufflesuite/ganache-core#11]
Since Web3 1.0.0 the HTTP provider no longer supports subscriptions (e.g listening for events).

Instead it is expected that developers use the new WebSocket provider or the IPC provider. Neither of these are supported by Ganache, and thus they are not supported in testrpc either.

## Expected Behavior
- Ganache should expose a WebSocket that accepts JSON-RPC as usual.
- Subscriptions should work as they did before Web3 1.0.0, but over WebSockets.

## Current Behavior
- WebSockets are unsupported.

## Context

It is impossible to use testrpc with Web3 1.0.0. Instead developers are forced to use Parity or geth.

**Comment by rodney757** [comment]
I have implemented basic support for websockets as well as a few pubsub types (`logs` and `newPendingTransactions`) in my fork (https://github.com/perissology/ganache-core)

There are not any websocket tests currently, and websocket have not been thoroughly tested yet. If someone would like to help with that, go ahead. If not, I hope to have time to finish the websocket integration withing the next month or so.

After I have a chance to write tests, I'll make a PR here.

**Comment by perissology** [comment]
I have implemented basic support for websockets as well as a few pubsub types (logs and newPendingTransactions) in my fork (https://github.com/perissology/ganache-core)

There are not any websocket tests currently, and websocket have not been thoroughly tested yet. If someone would like to help with that, go ahead. If not, I hope to have time to finish the websocket integration withing the next month or so.

After I have a chance to write tests, I'll make a PR here.

**Comment by miss61008596** [comment]
yes，
$geth --datadir data --networkid 31415926 --ws --wsport 8546 --wsorigins "*" --rpc --rpcport 8545 --rpccorsdomain "*" --nodiscover console
I tried it's work!!!

**Comment by onbjerg** [comment]
I'm not sure what you mean, that's geth, not testrpc.

**Comment by miss61008596** [comment]
I switched to geth,and it's work, maybe provide some help,cheers.

**Comment by pplam** [comment]
@miss61008596 Hey guy, you know that told about geth?

**Comment by pplam** [comment]
@miss61008596  Hey guy, you know that you are talking about geth?

**Comment by onbjerg** [comment]
@miss61008596 I don't want to use geth for tests. testrpc is more lightweight and setup is easier.

**Comment by benjamincburns** [comment]
I hate to close this ticket, but I'm cleaning up issues today as part of our team process, and we tend to track issues for the ganache suite of repos over on [trufflesuite/ganache-cli](https://github.com/trufflesuite/ganache-cli/issues/). In this case, this ticket duplicates trufflesuite/ganache-cli#257. As such, lets move this conversation over there.

**Comment by froid1911** [comment]
ok, so no ws support at all.

**Comment by benjamincburns** [comment]
@froid1911 please reread my last comment more carefully.
