### ISSUE TITLE
Support a gasPrice of 0

### ISSUE THREAD

**Issue by edevil** [trufflesuite/ganache-core#120]
## Expected Behavior

We should be able to specify a gasPrice of 0.

## Current Behavior

Setting a gasPrice of 0 resets it to the default value.

## Context

I'm a ganache-cli user and there have been situations in which I have needed to emulate a private network in which the gasPrice was 0, and this is currently not possible with Ganache.

**Comment by benjamincburns** [comment]
I added a test which shows that it's possible to create a network with zero gasLimit. I'm guessing that the bug you were likely encountering was the one fixed in 45e88ff9.

**Comment by edevil** [comment]
Thanks!

**Comment by AyushyaChitransh** [comment]
I am a ganache GUI user but I am unable to use gasPrice of 0. 

Version: v1.3.0
Environment: Windows

**Comment by davidmurdoch** [comment]
@AyushyaChitransh 	I have opened a new issue for this in the ganache (ui) repo: https://github.com/trufflesuite/ganache/issues/1119
