### ISSUE TITLE
Implement step tracker in `eth_estimateGas`

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache-core#147]
Implement a `step` handler to the EVM, tracking the stipend-requiring opcodes being executed in order to more accurately estimate gas.

Related to https://github.com/trufflesuite/ganache-core/pull/75 and https://github.com/trufflesuite/ganache-core/issues/26

**Comment by perissology** [comment]
any progress on this or plans to implement in the near future?

**Comment by benjamincburns** [comment]
trufflesuite/ganache-cli#592 is related

**Comment by davidmurdoch** [comment]
This should now be fixed in the latest **beta** tagged releases of ganache-cli and ganache-core.

This fix involved pretty significant code changes; check out the [release notes](https://github.com/trufflesuite/ganache-core/releases/tag/v2.5.4-beta.2) for details.

**We'd love it if you'd test this beta out to make sure things are good to go before we release to stable.** 

If you using `ganache-cli`, run: 

```console
npm install -g ganache-cli@beta
```

If you are using `ganache-core`, run:

```console
npm install ganache-core@beta
```

Let us know if you discover any bugs with this new beta release! Thanks!
