### ISSUE TITLE
FakeTransaction does not set ._from

### ISSUE THREAD

**Issue by IncentiveLoop** [trufflesuite/ganache-core#167]
## Expected Behavior
Ganache should allow you to set the `._from` property on FakeTransactions so that signatures can be ignored.

## Current Behavior
You cannot currently set `._from` on a FakeTransaction. This is because [FakeTransaction](https://github.com/ethereumjs/ethereumjs-tx/blob/master/fake.js#L54) expects data.from to be defined in order to [successfully set ._from](https://github.com/ethereumjs/ethereumjs-tx/blob/master/fake.js#L47). At the moment Ganache [passes in a Buffer to FakeTransaction](https://github.com/trufflesuite/ganache-core/blob/develop/lib/statemanager.js#L262) and data.from is undefined.

**Comment by davidmurdoch** [comment]
Closing, as ethereumjs-vm doesn't support fake transactions anymore.
