### ISSUE TITLE
Implement Constantinople

### ISSUE THREAD

**Issue by eggy-eth** [trufflesuite/ganache-core#200]

**Comment by davidmurdoch** [comment]
Thanks, @eggy-eth. You can track progress of Constantinople implementation at https://github.com/ethereumjs/ethereumjs-vm/projects/1

**Comment by stskeeps** [comment]
ethereumjs-vm has this in 2.5.0, any plans to move to that?

**Comment by davidmurdoch** [comment]
There are many breaking changes in 2.5.0 which we have been working towards fixing (both in ganache-core and ethereumjs-vm).

**Comment by PhABC** [comment]
I understand you are probably rushing to complete this, but any ETA for a release?

**Comment by nicholasjpaterno** [comment]
@PhABC we've just released a beta (implementing [EIP-1013](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1013.md)).  You can find the release [here](https://github.com/trufflesuite/ganache-core/releases) or using `npm install ganache-core@beta`

Please let us know if you experience any issues or anomalies!
