### ISSUE TITLE
JSON RPC calls that return a transaction have "input": null

### ISSUE THREAD

**Issue by timmclean** [trufflesuite/ganache-core#220]
## Expected Behavior
JSON RPC calls like `eth_getTransactionByHash` and `eth_getBlockByHash` return transaction objects. The `"input"` property of a transaction object should be `"0x"` if the transaction data is an empty array of bytes.

## Current Behavior
The `"input"` property of transaction objects is currently set to `null` if the transaction data is an empty array of bytes. This doesn't seem to be permitted by the [JSON RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_gettransactionbyhash) and causes compatibility issues.

## Possible Solution
It looks like the issue is in using `nullableRpcDataHexString` when the field isn't nullable:
https://github.com/trufflesuite/ganache-core/blob/0c3979d088e4de63798fef157532fd43aec18280/lib/utils/txhelper.js#L26

## Steps to Reproduce
In the truffle console:
```
web3.eth.getAccounts().then(ethaccounts => accounts = ethaccounts)
web3.eth.sendTransaction({from: accounts[0], to: accounts[1], value: web3.utils.toWei('10', "ether"), gas:50000, data: '0x'})
```
Then use, e.g., a `eth_getBlockByNumber(0x1, true)` JSON RPC call to get the block containing the new transaction.

## Context
The [rust-web3 crate](https://github.com/tomusdrw/rust-web3/) experiences parsing errors when receiving responses to its JSON RPC request due to the unexpected null value.

## Your Environment
ganache-cli & ganache-core, both on latest commit of develop branch.
Tested on Mac OS X.

**Comment by nicholasjpaterno** [comment]
Thanks @timmclean for reporting this.  We've issued a fix and it's just in time for our next release!

**Comment by timmclean** [comment]
Awesome thanks!!
