### ISSUE TITLE
Ambiguous `eth_call` revert results (behaves like Geth)

### ISSUE THREAD

**Issue by dekz** [trufflesuite/ganache-core#222]
As with Geth, when an `eth_call` reverts (and the function has no return data) it results in an ambiguity. Did this contract call fail or did it complete successfully with no return data?

Parity avoids this issue as it returns a different payload in the result of a revert.

We are attempting to standardise this behaviour and the [on-going discussion is here](https://ethereum-magicians.org/t/eip-remote-procedure-call-specification/1537/14). 

Successful Response via `eth_call` with no return specified:
```
// Ropsten
{"jsonrpc":"2.0","id":3,"result":"0x"}
// Kovan
{"jsonrpc":"2.0","id":1,"result":"0x"}
// Ganache 
{"id":1,"jsonrpc":"2.0","result":"0x0"}
```

Revert response
```
// Kovan
{"jsonrpc":"2.0","id":2005073035,"error":{"code":-32015,"data":"Reverted 0x","message":"VM execution error."}}
// Ropsten
{"jsonrpc":"2.0","id":2580139779,"result":"0x"}
// Ganache
{"id":1,"jsonrpc":"2.0","result":"0x0"}
```

Revert with Reason response:
```
// Geth
{"jsonrpc":"2.0","id":7,"result":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000104f524445525f554e46494c4c41424c4500000000000000000000000000000000"}
// Parity
{"jsonrpc":"2.0","id":4,"error":{"code":-32015,"data":"Reverted 0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000104f524445525f554e46494c4c41424c4500000000000000000000000000000000","message":"VM execution error."}}
// Ganache
{"id":3,"jsonrpc":"2.0","result":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000104f524445525f554e46494c4c41424c4500000000000000000000000000000000"}
```

## Expected Behavior
Determine the difference between a revert and a successful `eth_call` result.

## Current Behavior
Ambiguous `eth_call` response from a revert compared with a successful result from a contract with no return data.

## Possible Solution
Behave in a similar manner to Parity indicating the result was a Revert.

## Steps to Reproduce (for bugs)
```
pragma solidity ^0.4.25;

contract Reverter {
    function getRevert() public view
    {
        require(false == true);
    }
    
    function testRevert() public
    {
        return getRevert();
    }
    
    function testSomething() public
    {
        require(true == true);
    }
}
```

1. `eth_call` on `testRevert`
2. Observe response
3. `eth_call` on `testSomething`
4. Observe response

## Context
Difficult to attempt an `eth_call` to validate a transaction will work before a user submits this transaction. Behaviour is similar to Geth. 

Would like your thoughts and if you could participate in the [discussion about RPC responses](https://ethereum-magicians.org/t/eip-remote-procedure-call-specification/1537/14).

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by davidmurdoch** [comment]
Thanks for letting us know about this, @dekz! We'll be sure to implement the spec that's decided by the EIP. I'm going to go ahead and close this and we'll keep watching the progress of the EIP and update Ganache accordingly.
