### ISSUE TITLE
Creating contracts from other contracts fails when the address is not stored

### ISSUE THREAD

**Issue by sz-piotr** [trufflesuite/ganache-core#223]
## Relevant code
```solidity
pragma solidity ^0.4.24;

contract Thing {}

contract Factory {
    address public thing;
    
    // this function reverts on ganache
    function somehowFail() public {
        new Thing();
    }
    
    // this does not
    function create() public {
        thing = new Thing();
    }    
}
```

## Expected Behavior
Having deployed the `Factory` contract calling the `somehowFail` method creates a `Thing` and does not revert. Calling the `create` method also creates a `Thing` and does not revert.

## Current Behavior
Having deployed the `Factory` contract calling the `somehowFail` causes a revert. Calling the `create` method creates a `Thing` and does not revert.
**Note** - calling `somehowFail` does not cause a revert when using the JavascriptVM on remix

## Possible Solution
Probably the bug is somehow linked to the fact that the address of the created contract is stored in the variable.

## Steps to Reproduce (for bugs)

1. Compile the code above in remix
2. Use a web3 provider of a local ganache-cli
3. Deploy `Factory`
4. Call `somehowFail`

## Context
We are implementing a contract that creates other contracts. We wanted to only use logs to store the created contract addresses but that failed because of this bug.

## Your Environment

* Version used: Ganache CLI v6.1.8 (ganache-core: 2.2.1), we also used the ganache-core package programmatically
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): nodejs v10.11.0
* Server type and version: n/a
* Operating System and version: macOS Mojave 10.14
* Link to your project: all the relevant code is in the issue

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache-cli/issues/573

**Comment by sz-piotr** [comment]
Why close this if the issue is not resolved?

**Comment by davidmurdoch** [comment]
@sz-piotr, there is a similar issue (trufflesuite/ganache-cli#573) that is now linked to this issue and we'll be tracking the issue there.

I'm sorry if closing the issue without comment made it seem like we were ignoring it; that is certainly not the case. I should have commented my intent when closing it.

Thanks for taking the time to write up the issue; it will be helpful when resolving it.
