### ISSUE TITLE
Is `evm_increaseBlock` to mine a number of empty blocks a desired function

### ISSUE THREAD

**Issue by adibas03** [trufflesuite/ganache-core#256]
Ganache-core has a method `evm_increaseTime`, but there is no corresponding `evm_increaseBlock` to increase by mining a number of empty block. I presently use a little code to make this possible.

```
const forceMine = async (value, isBlock) => {
  	//value: number of seconds or blocks to advance by
  	let count = 1;
  	if (!isBlock) {
  		 await web3.currentProvider.send({
  		   jsonrpc: "2.0",
  		   method: "evm_increaseTime",
  		   params: [value],
  		   id: new Date().getTime()
  		 });
  	 } else {
  		count = value;
  	}

  	 for( let i=0;i<count;i++) {
  		 await web3.currentProvider.send({
  		   jsonrpc: "2.0",
  		   method: "evm_mine",
  		   id: new Date().getTime()
  		 });
  	}
  }
```

## Expected Behavior
The function `evm_increaseBlock` would internally mine the provided number of empty blocks.  
  
`evm_increaseBlock(blocks)`  

## Current Behavior
Presently, there is no implementation for increasing blocks at the time.

## Context
This function would help in testing solidity functions which depend on the present block number, basically any function that has a start and stop dependent on the block number.

Would this function be desirable, I could create a PR for it.

**Comment by seesemichaelj** [comment]
Thanks for the feature request!

We [still do not](https://github.com/trufflesuite/ganache-core/issues/82) desire this functionality. We'd rather keep the functionality minimal and let users implement their own mechanisms to mine blocks as they see fit.

Thanks writing this up however, we really appreciate the contribution and the offer to implement it!

**Comment by chiro-hiro** [comment]
I think, this is useful at least for me :+1:

**Comment by fabdarice** [comment]
useful too. Would love this o be implemented.

**Comment by davidmurdoch** [comment]
@fabdarice ganache@v7.0.0-alpha.0 now has this feature as part of `evm_mine`. See the release notes here: https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.0#user-content-v7.0.0-alpha.0-new-features
