### ISSUE TITLE
MaxListenersExceededWarning encountered when running with Web3

### ISSUE THREAD

**Issue by adrianmcli** [trufflesuite/ganache-core#267]
For more detailed history: https://github.com/ethereum/web3.js/issues/1648

When running Ganache provider (for my tests) and then subsequently interacting them with Web3.js, I get warnings like the following:

```
(node:38062) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit
```

According to this specific [comment](https://github.com/ethereum/web3.js/issues/1648#issuecomment-431047839), the issue seems to be due to the Ganache Provider.

Interestingly, @cgewecke suppressed these warnings in Truffle in this PR: https://github.com/trufflesuite/truffle/pull/1088

Not exactly sure if this belongs here, but I believe it is worth the investigation.

**Comment by seesemichaelj** [comment]
The only _correct_ path forward within ganache (I believe that this is really a problem in web3.js which is adding listeners a little haphazardly) is to overload the `on()` function in the ganache provider and do some stuff to prevent the warning. Suppressing the warnings like the truffle PR is definitely not a great approach

**Comment by seesemichaelj** [comment]
Seems like this issue is being [dropped](https://github.com/trufflesuite/ganache-core/pull/269#issuecomment-648442131)
