### ISSUE TITLE
bug for transaction receipt event logs when multiple transactions are included in one block

### ISSUE THREAD

**Issue by davidbancor** [trufflesuite/ganache-core#273]
## Current Behavior
When calling web3.eth.getTransactionReceipt for a transaction which was mined with at least one other transaction in the same block, the event logs returned include the  event logs of every other transaction in that block. 

## Possible Solution
https://github.com/trufflesuite/ganache-core/pull/268

## Steps to Reproduce (for bugs)
send two signed transactions consecutively that both will emit events (ganache must be running with a fixed block time)

**Comment by balexander4** [comment]
This is a present issue I have validated and seen repeatedly, there are several calls that when used, ganache-cli displays the data back in an unexpected way. Will link the issues once I have tracked down all instances.

**Comment by davidmurdoch** [comment]
Fixed in #268
