### ISSUE TITLE
The tx doesn't have the correct nonce when calling `debug_traceTransaction`

### ISSUE THREAD

**Issue by LogvinovLeon** [trufflesuite/ganache-core#280]
## Expected Behavior
I expect ganache to return a transaction trace.

## Current Behavior
Currently it throws that error:
```bash
Error: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 1
    at /Users/leonidlogvinov/0x/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:117:12
    at /Users/leonidlogvinov/0x/ganache-core/node_modules/ethereumjs-vm/dist/cache.js:57:7
    at /Users/leonidlogvinov/0x/ganache-core/node_modules/ethereumjs-vm/dist/cache.js:44:5
    at /Users/leonidlogvinov/0x/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:77:5
    at /Users/leonidlogvinov/0x/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at Object.return (/Users/leonidlogvinov/0x/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:485:9)
    at processNode (/Users/leonidlogvinov/0x/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:285:30)
    at processNode (/Users/leonidlogvinov/0x/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:521:5)
    at /Users/leonidlogvinov/0x/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at /Users/leonidlogvinov/0x/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

It's surprising that this nonce issue doesn't happen when I send the transaction. It's successfully mined. And then when I ask for a trace it breaks with that message.

[Here](https://pastebin.com/EPeT4Uw5) is the ganache verbose log of what was happening before the failure.

## Steps to Reproduce (for bugs)
I've created a repro [branch](https://github.com/0xProject/dev-tools-truffle-example/tree/feature/ganache-nonce-issue-repro).

## Context
I'm trying to measure code coverage using debug traces, but I can't get them out of ganache because of that issue.

## Your Environment

* Version used: latest development using npm links (but latest published has the same problem)
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: Mac
* Link to your project: https://0x.org

**Comment by davidmurdoch** [comment]
My hunch is that when tracing the transaction with `debug_traceTransaction` the transaction reply hits the EVM's cache, which contains a stale nonce value from the initial transaction. I believe this has been fixed in the `develop` branch and will be in the next release.

I'll leave this issue open until I can confirm if its fixed or not. Thanks again, @LogvinovLeon!

**Comment by WyseNynja** [comment]
@davidmurdoch Have you been able to confirm if this is fixed or not?

**Comment by LogvinovLeon** [comment]
@davidmurdoch Ping

**Comment by davidmurdoch** [comment]
@LogvinovLeon 	When running `yarn && yarn test` on the provided repository (on branch `feature/ganache-nonce-issue-repo`) the test passes (`1 passing`). Do I need to change the truffle-config in order to reproduce?

**Comment by LogvinovLeon** [comment]
@davidmurdoch My bad. I just confirmed that the newest release of Ganache has it fixed! Thanks!
Now you can use @0x/sol-trace and @0x/sol-coverage with Ganache.

**Comment by dikshasonics2000** [comment]
"TXRejectedError: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 4\n" +
      '    at validateNonce (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\lib\\statemanager.js:1017:11)\n' +
      '    at C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\lib\\statemanager.js:1026:7\n' +   
      '    at C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\lib\\blockchain_double.js:444:5\n' 
+
      '    at C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\merkle-patricia-tree\\baseTrie.js:97:9\n' +
      '    at C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\merkle-patricia-tree\\baseTrie.js:520:18\n' +
      '    at Object._return [as return] (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\merkle-patricia-tree\\baseTrie.js:545:13)\n' +
      '    at processNode (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\merkle-patricia-tree\\baseTrie.js:328:34)\n' +
      '    at processNode (C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\merkle-patricia-tree\\baseTrie.js:579:9)\n' +
      '    at C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\merkle-patricia-tree\\baseTrie.js:574:17\n' +
      '    at C:\\Program Files\\WindowsApps\\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache-core\\node_modules\\merkle-patricia-tree\\baseTrie.js:212:11\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:75:11)',
    name: 'TXRejectedError'
  }
}


Ca
![Screenshot (523)](https://user-images.githubusercontent.com/53328579/222944958-192aba7c-3414-4731-bf25-617208ef4e7e.png)Can someone tell how to solve this, I am sending a transaction and using ganache provider for this. But i dont know whts wrong with this nonce

**Comment by davidmurdoch** [comment]
@dikshasonics2000 try updating ganache UI to v 2.7
0 https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.0

**Comment by dikshasonics2000** [comment]
> @dikshasonics2000 try updating ganache UI to v 2.7 0 https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.0

Yes i will try doing that, thanks for the help :)
