### ISSUE TITLE
Calling a contract at a specific block which has since called selfdestruct fails

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/ganache-core#288]
With the logic from https://github.com/trufflesuite/ganache-core/pull/69 it became possible to execute `eth_call` [passing in a blockNumber option](https://github.com/ethereum/wiki/wiki/JSON-RPC#the-default-block-parameter). This works well in the cases where the contract we're calling still exists at the current block, however if that had called `selfdestruct` since the requested `blockNumber` required, the call fails.

## Expected Behavior
The call should succeed if it's made against a blockNumber where the contract still existed, i.e. at a point before `selfdestruct` was called.

## Current Behavior
Such calls fail.

## Possible Solution
We have been running with a [patched version](https://github.com/area/ganache-cli.git#fakefix/eth_call_selfdestruct) of `ganache-core` @area did back in August last year which works. 

## Steps to Reproduce (for bugs)
[Sample CI build](https://circleci.com/gh/JoinColony/colonyNetwork/6037)

## Your Environment
* Version used: 6.2.5
* Operating System and version: MacOS High Sierra
* Link to your project: https://github.com/JoinColony/colonyNetwork

**Comment by ccowell** [comment]
@elenadimitrova Still need to validate this issue but we believe this commit may resolve the issue.

https://github.com/trufflesuite/ganache-core/commit/e9a54a4c64f7aaa1b832fc9d7c6d85ab479deb32
