### ISSUE TITLE
Consolidate setup/teardown logic to mocha hooks

### ISSUE THREAD

**Issue by ccowell** [trufflesuite/ganache-core#296]
## Expected Behavior
Expecting setup and teardown logic to be placed into appropriate mocha `hooks`

## Current Behavior
A lot of these tests have the same test setup. You may be able to easily add the test set up to a beforeEach and/or afterEach, or maybe make use of ganache's snapshot/revert feature so the tests don't have to do the reset.

**Comment by davidmurdoch** [comment]
For posterity: I intended this to be related to gas.js tests,  but i'm sure it does apply to many other tests as well.
