### ISSUE TITLE
Add `eth_chainId` RPC endpoint

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache-core#339]
https://github.com/ethereumproject/go-ethereum/wiki/JSON-RPC#eth_chainid

**Comment by fireblockdev** [comment]
After discussion with nividia from web3js, this method is needed to use ganache with web3js.

**Comment by fireblockdev** [comment]
I did the same but he didn't fix the problem for me

**Comment by projectoblio** [comment]
Thank you @tcichowicz for not being a psycho capitalist

**Comment by projectoblio** [comment]
@davidmurdoch Is this issue closed now with the push today? Tcichowicz code should be merged right

**Comment by lucashenning** [comment]
Any update on this? The issue in the web3.js repo has been closed (https://github.com/ethereum/web3.js/issues/2610) but I'm still getting the same error in web3 `1.0.0-beta.55` and Ganache `2.0.2-beta.0 (2.0.2-beta.0.648)`.

```
{"message":"Method eth_chainId not supported.","code":-32000,"data":{"stack":"Error: Method eth_chainId not supported.\n    at GethApiDouble.handleRequest (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/lib/subproviders/geth_api_double.js:67:16)\n    at next (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:116:18)
```

**Comment by imbenwolf** [comment]
@davidmurdoch please review #419 so we can finally use latest web3 and ganache versions together

**Comment by davidmurdoch** [comment]
I've hesitated adding this as the value it returns should be configurable. I'll go ahead and merge this into develop now regardless and follow up with a new Issue to add a chain_id configuration option to core, cli, and UI.

Thanks for keeping on top of this @imbenwolf and @lucashenning!

Aside, it may be worth it to know that web3@beta.37 is the version of web3 that will be released as stable. PR here: https://github.com/ethereum/web3.js/pull/2905

**Comment by davidmurdoch** [comment]
Followup issue: https://github.com/trufflesuite/ganache-core/issues/441

Thanks again!

**Comment by saurik** [comment]
Is this API supposed to be live on https://public-node.rsk.co/?

```
$ curl -s -X POST --data '{"jsonrpc":"2.0","id":"","method":"eth_chainId","params":[]}' -H 'content-type: application/json' https://public-node.rsk.co/
{"jsonrpc":"2.0","id":"","error":{"code":-32603,"message":"Internal server error"}}
```

**Comment by saurik** [comment]
(To anyone who got an e-mail notification with a weird follow-up question from me on this old issue, I left it on the wrong issue as this had a similar name to an issue from another project I had open.)
