### ISSUE TITLE
Allow List of Addresses in Filter

### ISSUE THREAD

**Issue by hayesgm** [trufflesuite/ganache-core#34]
## Expected Behavior
Filters are used to track changes (e.g. new logs from a given contract address). According to the [JSON-RPC spec](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newfilter) for `eth_newFilter`, the `address` field should be:

> `address`: `DATA|Array`, 20 Bytes - (optional) Contract address or a list of addresses from which logs should originate.

The address is allowed to be either:
 * null (to watch everything)
 * a single address to watch
 * an array of addresses to watch

## Current Behavior
Currently in ganache, filters work for `null` or for a single address. When an array of addresses is passed in to `eth_newFilter` to ganache-core, the resulting filter always return blank (no matches). This is in violation of the spec above.

## Possible Solution
[StateManager.prototype.getLogs](https://github.com/trufflesuite/ganache-core/blob/develop/lib/statemanager.js#L601) should allow `filter.address` to be an array and handle that case appropriately. This should be a minor change.

## Steps to Reproduce (for bugs)
1. Deploy any contract with any public function which produces a log (event)
2. Create a new filter with `address=<address from above>`
3. View logs associated with that filter
4. Created a new filter with `address=[<address from above>]` (that is, an array)
5. See no logs associated with that filter

## Context
Implementing JSON-RPC / web3 correctly is an important goal for ganache and Truffle.

## Your Environment
* Version used: Truffle v4.0.1 (core: 4.0.1)

**Comment by seesemichaelj** [comment]
This was fixed in https://github.com/trufflesuite/ganache-core/pull/130
