### ISSUE TITLE
Investigate if the genesis block created when forking is neccessary.

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache-core#341]
The goal is to ensure that the first block mined after initializing a forking provider with a `fork_block_number` is `fork_block_number + 1`, not `fork_block_number + 2` as it is now.

Something to keep in mind here is that we need need to be able to store the initial accounts and if we don't create an initial block where does this data get stored?

If it does still work in memory will it work with a persisted DB? This question is possibly blocked by: https://github.com/trufflesuite/ganache-core/issues/340, if the tests there prove that this doesn't actually work.

**Comment by gnidan** [comment]
@davidmurdoch reports that he is now smarter and that this is, in fact, necessary.
