### ISSUE TITLE
Question - Is it possible to console.log events once it happened for debug ? 

### ISSUE THREAD

**Issue by askucher** [trufflesuite/ganache-core#352]
I did not find the topic "how to watch events" in documentation/tests. 

I expect something like `web3.eth.watch.logs()` based on eth_filterLogs. 

Maybe you have an example of how to make it with ganache-core

**Comment by nicholasjpaterno** [comment]
Thanks for the question @askucher! Im wondering if you're looking for `subscribe`?  Something like this: https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#subscribe-logs

Make sure to connect to ganache over websocket, `subscribe` is not supported through HTTP.

**Comment by askucher** [comment]
Thank you for answer @nicholasjpaterno . I will try and publish results here

**Comment by askucher** [comment]
I got managed it with 

```Javascript 
const contract = new web3.eth.Contract(abi, address)

contract.once("Transfer", {}, callback);
```

It works in 100% percent of my tests.
