### ISSUE TITLE
Number can only safely store up to 53 bits error on debug.traceTransaction on a forked TestRPC

### ISSUE THREAD

**Issue by InsidiousMind** [trufflesuite/ganache-core#36]
## Expected Behavior

web3 traceTransaction should go through on a forked TestRPC

## Current Behavior

get `Error: Number can only safely store up to 53 bits`

Should be able to handle traceTransaction when testRPC is forked. traceTransaction on a non-forked TestRPC works fine.

## Steps to Reproduce (for bugs)
- Run ./cli.js with default options
- Create a new Ganache Instance with Fork Options (from my setup): 
```javascript
const ForkOptions = {
  port: '8546',
  hostname: 'localhost',
  debug: false,
  seed: null,
  mnemonic: null,
  total_accounts: null,
  blocktime: null,
  gasPrice: null,
  gasLimit: 3000000, // 3mil gas
  accounts: null, // was parseAccounts(accounts)
  unlocked_accounts: [0],
  fork: 'http://localhost:8545',
  network_id: null,
  verbose: false,
  secure: null,
  db_path: null,
  account_keys_path: null,
  logger: console,
};
```
- try sending traceTransaction to forked TestRPC as such:
```javascript
var options = {
  disableStorage: true,
  disableMemory: false,
  disableStack: false,
  fullStorage: false,
 };
 web3.debug.traceTransaction(<YOUR_TX_HASH>, options, function (error, result) {
    callback(error, result);
 });
```
## Context

Building a Debugger for Solidity. One of the options is to run debugger on a forked TestRPC.

## Your Environment

* Version used: Latest Ganche-core 
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Node.JS V 9.1.0
* Server type and version: N/A
* Operating System and version: ArchLinux 4.14.3-1-ARCH

**Comment by benjamincburns** [comment]
Thanks for reporting this, @InsidiousMind. Let's track this one over on trufflesuite/ganache-cli#439.
