### ISSUE TITLE
Filters and getLogs supports only single address, not an array

### ISSUE THREAD

**Issue by drdaeman** [trufflesuite/ganache-core#38]
It seems multiple addresses for `eth_newFilter` and `eth_getLogs` are not supported. Unlike geth (which has `address: DATA|Array`), ganache is only capable of filtering on a single address. If an array is passed (even with only a single item in it), ganache will always return an empty list, not matching anything.

Here's the relevant code:

https://github.com/trufflesuite/ganache-core/blob/d1646364d7e4ad667e4c522e0d7877bc962ba949/lib/statemanager.js#L601

As you can see, it only has equality check, so it would fail in presence of array. An obvious fix would be to check for type - e.g. do something in lines of

    return expectedAddress == null || (
        Array.isArray(expectedAddress)
            ? expectedAddress.includes(log.address)
            : log.address == expectedAddress);

But - sorry - I'm to lazy to make a proper pull request.

(Copied from https://github.com/trufflesuite/ganache-cli/issues/322#issuecomment-353109875 where I've originally posted it. Found the relevant code in this project, so posting it here.)

**Comment by seesemichaelj** [comment]
The `getLog` implementation for this was fixed in https://github.com/trufflesuite/ganache-core/pull/130

If you're still having issues with `newFilter`, that call is forwarded to https://github.com/MetaMask/provider-engine which should support multiple addresses
