### ISSUE TITLE
Remove Gas Estimation TODOs (probably by fixing them)

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache-core#384]
- [x] Assert op must be a System op: CREATE/CALL/etc https://github.com/trufflesuite/ganache-core/blob/fe5ed79e8f47fce12dd9019bdfe764cb2cf95ab8/lib/utils/gasEstimation.js#L160-L161 https://github.com/trufflesuite/ganache-core/blob/fe5ed79e8f47fce12dd9019bdfe764cb2cf95ab8/lib/utils/gasEstimation.js#L203-L204
- [ ] Make gas test actually test SVT https://github.com/trufflesuite/ganache-core/blob/fe5ed79e8f47fce12dd9019bdfe764cb2cf95ab8/test/gas/gas.js#L177-L178

**Comment by gnidan** [comment]
The implementation currently has no TODOs. Hooray! Closing.
