### ISSUE TITLE
eve_mine with timestamp parameter is some times off by one second

### ISSUE THREAD

**Issue by pieterhartel** [trufflesuite/ganache-core#388]
`evm_mine` with timestamp parameter is some times off by one second. This is not helpful as deterministic behaviour of contracts is often desirable when hunting for bugs.

## Expected Behavior
I would expect `evm_mine` with timestamp to deliver a block with exactly the given timestamp.

## Current Behavior
I call `evm_mine` with a timestamp parameter, which usually is honoured but not always. This is an intermittent problem.  Below I provide two sample outputs of a test contract in Truffle, which differ only in the timestamps of block 14.

Here is the first output, with block 14 having a time stamp 1600000071
```
$ truffle test
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...

  Contract: MetaCoin
block.number 5 block.timestamp 1552999213 timestamp 1600000000
1 'blockNumber' 6
    ✓ TEST 1: should deploy (42ms)
block.number 6 block.timestamp 1600000000 timestamp 1600000020
2 'blockNumber' 7
    ✓ TEST 2: should put 10000 MetaCoin in the first account (69ms)
block.number 7 block.timestamp 1600000020 timestamp 1600000030
3 'blockNumber' 8
    ✓ TEST 3: should fail because function does not exist on contract
block.number 8 block.timestamp 1600000030 timestamp 1600000040
4 'blockNumber' 9
    ✓ TEST 4: should call a function that depends on a linked library (85ms)
block.number 9 block.timestamp 1600000040 timestamp 1600000050
5 'blockNumber' 10
    ✓ TEST 5: should send coin (109ms)
block.number 11 block.timestamp 1600000050 timestamp 1600000060
6 'blockNumber' 12
    ✓ TEST 6: should not send coin (54ms)
block.number 12 block.timestamp 1600000060 timestamp 1600000070
7 'blockNumber' 13
    ✓ TEST 7: should send coin correctly (227ms)
block.number 14 block.timestamp 1600000071 timestamp 1600000080
8 'blockNumber' 15
0 'blockNumber' 0 'timeStamp' 1552999209
1 'blockNumber' 1 'timeStamp' 1552999212
2 'blockNumber' 2 'timeStamp' 1552999212
3 'blockNumber' 3 'timeStamp' 1552999213
4 'blockNumber' 4 'timeStamp' 1552999213
5 'blockNumber' 5 'timeStamp' 1552999213
6 'blockNumber' 6 'timeStamp' 1600000000
7 'blockNumber' 7 'timeStamp' 1600000020
8 'blockNumber' 8 'timeStamp' 1600000030
9 'blockNumber' 9 'timeStamp' 1600000040
10 'blockNumber' 10 'timeStamp' 1600000050
11 'blockNumber' 11 'timeStamp' 1600000050
12 'blockNumber' 12 'timeStamp' 1600000060
13 'blockNumber' 13 'timeStamp' 1600000070
14 'blockNumber' 14 'timeStamp' 1600000071
15 'blockNumber' 15 'timeStamp' 1600000080
    ✓ TEST 8: check all addresses (234ms)

  8 passing (904ms)
```

Here is the second output with block 14 having a time stamp 1600000070
```
$ truffle test
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...

  Contract: MetaCoin
block.number 5 block.timestamp 1552999262 timestamp 1600000000
1 'blockNumber' 6
    ✓ TEST 1: should deploy (39ms)
block.number 6 block.timestamp 1600000000 timestamp 1600000020
2 'blockNumber' 7
    ✓ TEST 2: should put 10000 MetaCoin in the first account (67ms)
block.number 7 block.timestamp 1600000020 timestamp 1600000030
3 'blockNumber' 8
    ✓ TEST 3: should fail because function does not exist on contract
block.number 8 block.timestamp 1600000030 timestamp 1600000040
4 'blockNumber' 9
    ✓ TEST 4: should call a function that depends on a linked library (91ms)
block.number 9 block.timestamp 1600000040 timestamp 1600000050
5 'blockNumber' 10
    ✓ TEST 5: should send coin (119ms)
block.number 11 block.timestamp 1600000050 timestamp 1600000060
6 'blockNumber' 12
    ✓ TEST 6: should not send coin (57ms)
block.number 12 block.timestamp 1600000060 timestamp 1600000070
7 'blockNumber' 13
    ✓ TEST 7: should send coin correctly (228ms)
block.number 14 block.timestamp 1600000070 timestamp 1600000080
8 'blockNumber' 15
0 'blockNumber' 0 'timeStamp' 1552999258
1 'blockNumber' 1 'timeStamp' 1552999261
2 'blockNumber' 2 'timeStamp' 1552999261
3 'blockNumber' 3 'timeStamp' 1552999262
4 'blockNumber' 4 'timeStamp' 1552999262
5 'blockNumber' 5 'timeStamp' 1552999262
6 'blockNumber' 6 'timeStamp' 1600000000
7 'blockNumber' 7 'timeStamp' 1600000020
8 'blockNumber' 8 'timeStamp' 1600000030
9 'blockNumber' 9 'timeStamp' 1600000040
10 'blockNumber' 10 'timeStamp' 1600000050
11 'blockNumber' 11 'timeStamp' 1600000050
12 'blockNumber' 12 'timeStamp' 1600000060
13 'blockNumber' 13 'timeStamp' 1600000070
14 'blockNumber' 14 'timeStamp' 1600000070
15 'blockNumber' 15 'timeStamp' 1600000080
    ✓ TEST 8: check all addresses (229ms)

  8 passing (914ms)
```

## Possible Solution
I'm sorry, I have no idea.

## Steps to Reproduce (for bugs)
Here is the truffle code needed to reproduce the issue: 
[MetaCoin.zip](https://github.com/trufflesuite/ganache-core/files/2983368/MetaCoin.zip)

$ unzip MetaCoin.zip
$ cd MetaCoin
$ truffle test
... keep trying until the behaviour changes
$ truffle test 

## Context
I am trying to debug smart contracts that use `now.` It would be most helpful if the contracts could be made to behave deterministically.

## Your Environment
```
$ truffle version
Truffle v5.0.2 (core: 5.0.2)
Solidity v0.5.0 (solc-js)
Node v10.15.0
$ uname -a
Darwin 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

**Comment by pieterhartel** [comment]
After having spent an afternoon on this I think that I might have found what causes the problem. The test script controls the timestamp of some blocks but there are still blocks that are auto-mined. For example, block 14 is auto-mined, and apparently, it does not always have the same time stamp. This begs the question: Can I switch auto-mining off? I believe that auto-mining is needed while the contract is being deployed, so I'd like to switch it off once my test script gains control.

**Comment by davidmurdoch** [comment]
Thanks @pieterhartel for the detailed reproduction steps!

This apparent non-determinism is caused by ganache "instamining"; that is to say: it mines a new block immediately after a transaction is received.

`evm_mine(timestamp)` causes a block to be mined _exactly_ at the timestamp given, and also updates the internal `timeAdjustment` (this basically lets us fast-forward or rewind time) so blocks mined in the future always happen _after_ the last block mined. Block timestamps are still based on the real clock though, just with this `timeAdjustment` added in.

The amount of time between `evm_mine` and your next transaction is not going to be `0`, and _sometimes_ the time difference will span two different _real_ seconds -- and this can happen even if the difference is a single millisecond. This is what causes the block timestamps vary in your tests.

To make your tests deterministic you should:

1) start ganache with the `time` option (in addition to a deterministic seed/mnemonic option). This will create a genesis block at the given timestamp (there is actually a bug here so this part might not always happen perfectly).
2) Send a `miner_stop` RPC call to prevent any more blocks from being insta-mined.
3) Send the transaction or transactions you want mined in the next block
4. Send an `evm_mine` RPC call with a timestamp to cause the transaction(s) you sent in step 3 to be mined at the specific timestamp.

Let me know if you have an questions. Thanks again!

**Comment by pieterhartel** [comment]
Dear @davidmurdoch, Thank you for the explanation. I have implemented your suggestion and it seems that I have to execute step 4 twice. Why would that be?

**Comment by davidmurdoch** [comment]
Are you saying you have to send `evm_mine` twice in order to mine the transactions you sent in step 3?

**Comment by pieterhartel** [comment]
Indeed but not on the MetaCoin example above, but on another contract. I am having some difficulty reproducing the behaviour with a manageable example; I need to spend some more time on this.

I do have another question though on the MetaCoin example. With the -t option I can set the time stamp of block 0, but how do I control the timestamp of block numbers 1 to 5?  To begin with I cannot even access web3 in a migration script.

**Comment by pieterhartel** [comment]
@davidmurdoch I have tried to repeat the problem of the double `evm_mine` here: 
[Vitaluck.zip](https://github.com/trufflesuite/ganache-core/files/2989524/Vitaluck.zip)

In the file `test/vitaluck.js` there are two occurrences of the statement ` await mine_time.mineBlockWithTimestamp( 1600000000 ) ;`. If one is commented out the test will hang, trying to get a receipt which will never happen. If the statement is active the output is as shown below.

```
$ truffle test
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/Vitaluck.sol...


  Contract: Vitaluck
    ✓ TEST: Vitaluck (60ms)
    ✓ TEST: Play(  ) (117ms)
0 1553105024 0
1 1553105028 1
2 1553105029 1
3 1553105029 1
4 1553105029 1
5 1500000000 0
6 1500000000 0
7 1500000000 0
8 1600000000 0
9 1600000000 0
10 1600000000 1
    ✓ TEST: check all blocks (98ms)


  3 passing (311ms)
```

**Comment by davidmurdoch** [comment]
As for controlling the first timestamp of those initial blocks... could you open a [new issue over on the Truffle repo](https://github.com/trufflesuite/truffle/issues/new?title=Feature%20Request:%20Control%20the%20timestamp%20of%20initial%20block%20numbers)?

---

RE Vitaluck.js: This is because when you call `evm_mine` the first time the JSON RPC call to `deployed()` either hasn't yet been received or just hasn't yet been processed by Ganache -- so there are no pending transactions for it to mine yet.

What you'll need to do is use [`.new()`](https://truffleframework.com/docs/truffle/reference/contract-abstractions#-code-mycontract-new-arg1-arg2-tx-params-code-) instead of `.deployed()`, as `.new()` returns a `promiEvent`:

```
const deployRequest = Vitaluck.new( );
await new Promise((resolve) => {deployRequest.on("transactionHash", resolve)});
await mine_time.mineBlockWithTimestamp( 1500000000 ) ;
deployedContract = await deployRequest ;
```

and similarly with the contract methods:

```
const txRequest = deployedContract.methods[ "Play()" ]( txOptions ) ;
await new Promise((resolve) => {txRequest.on("transactionHash", resolve)});
await mine_time.mineBlockWithTimestamp( 1600000000 ) ;
const txResult = await txRequest ;
```

**Comment by pieterhartel** [comment]
@davidmurdoch Thanks very much for the suggested code fragments.

I have tried your suggestions out and it works well for contracts without constructor arguments. If there are constructor arguments I get something like this:
`Uncaught Error: Invalid number of parameters for "undefined". Got 0 expected 2!`

The constructor arguments are in the migration script, but that no longer works. For example if Vitaluck would have two arguments, the relevant part of the migration script would have looked like this:
```
	const txOptions = { from: accounts[5], value: "0", to: 0 }
	deployer.deploy( Vitaluck, **arg1, arg2**, txOptions ) ;
```
So my question is where do I put the constructor arguments? And where do the `txOptions` go?

**Comment by davidmurdoch** [comment]
The truffle docs for [new](https://truffleframework.com/docs/truffle/reference/contract-abstractions#-code-mycontract-new-arg1-arg2-tx-params-code-
) should have the answer.

> **MyContract.new([arg1, arg2, ...], [tx params])**
> 
> This function take whatever contructor parameters your contract requires and deploys a new instance of the contract to the network. There's an optional last argument which you can use to pass transaction parameters including the transaction from address, gas limit and gas price. This function returns a Promise that resolves into a new instance of the contract abstraction at the newly deployed address.

Let me know if that doesn't answer your question.

**Comment by pieterhartel** [comment]
Dear @davidmurdoch ,

Thanks for you swift answer. Am I right in thinking that with using  `.new()` instead of `.deploy()` some of the functionality is shifting from the migration to the test script? The reason I am asking is because on this page [https://truffleframework.com/docs/truffle/getting-started/running-migrations ](url) the arguments are also mentioned.

**Comment by davidmurdoch** [comment]
`deployed()` in your test scripts assumes you're using migrations and they've already run.

It sounds like you could still use `deploy` (instead of `new`) in your _migrations_ (and not in the tests themselves) in combination with `miner_stop`/`miner_start` and `evm_mine`.

**Comment by pieterhartel** [comment]
Dear @davidmurdoch, thank you one again for the swift response. I believe that I found a solution by dispensing with the second migration script altogether!

Here is a fresh zip file [Vitaluck.zip](https://github.com/trufflesuite/ganache-core/files/3057080/Vitaluck.zip) with a modified version of Vitaluck. I have added a constructor with an argument that is set in the test script as follows:
```
const txOptions = { from: accounts[5], value: "0", to: 0 } ;
const deployRequest = Vitaluck.new( 5000000, txOptions ) ;
```

The results show that (1) the constructor (in block 3) and the methods (in blocks 4 & 5) execute with `now` set to specific values; (2) the first method call succeeds and the second method call fails.

```
$ truffle test --show-events
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/Vitaluck.sol...

  Contract: Vitaluck
    ✓ TEST: Vitaluck( 5000000 ) (1075ms)

    Events emitted during test:
    ---------------------------
    Configure(timestamp: 1500000000, minBetValue: 5000000)
    ---------------------------
    ✓ TEST: Play( ) this should succeed (1055ms)

    Events emitted during test:
    ---------------------------
    NewPlay(timestamp: 1600000000, player: 0x821aEa9a577a9b44299B9c15c88cf3087F3b5544, number: 0, won: false)
    ---------------------------
    1) TEST: Play( ) this should fail
    > No events were emitted
0 1554781716 0
1 1554781721 1
2 1554781721 1
3 1500000000 1
4 1600000000 1
5 1700000000 1
    ✓ TEST: check all blocks (82ms)
    > No events were emitted


  3 passing (3s)
  1 failing

  1) Contract: Vitaluck
       TEST: Play( ) this should fail:
     Error: Transaction: 0x34a0205add73c32d20cfffcd5230bad90430489ad884ad16e9cd1b6b5b4c22b2 exited with an error (status 0).
     Reason given: value less than minBetValue.
```

**Comment by pieterhartel** [comment]
@davidmurdoch some of my transactions now timeout after 750 seconds.

`Transaction was not mined within750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!`

I'm trying to reproduce it in a small test but that's not easy. Would it be possible to improve the code that you suggested to make such timeouts impossible, or at least a lot less likely? 

```
const txRequest = deployedContract.methods[ "Play()" ]( txOptions ) ;
await new Promise((resolve) => {txRequest.on("transactionHash", resolve)});
await mine_time.mineBlockWithTimestamp( 1600000000 ) ;
const txResult = await txRequest ;
```
