### ISSUE TITLE
Support in browser

### ISSUE THREAD

**Issue by Tristyn** [trufflesuite/ganache-core#39]
It seems like Ganache core is close to being able to run in-browser. It's dependency 'leveldown' require a node environment, this could be swapped out for level-js when in a browser environment. There may be other issues when I dig into this.

## Expected Behaviour
Ganache-core runs on html5

## Actual Behaviour
Ganache throws an exception when required(), cannot initialize it's leveldown dependency.

## Context

It'd be nice to run a private chain in-browser to allow users to testdrive a dapps functionality without using a test network and with minimal or no network usage. Alternatives are to run a websocket to a node server running ganache, or to abstract over the web3 layer entirely.

I'm going to tinker with this idea soon.

**Comment by benjamincburns** [comment]
@Tristyn this is a great request - something I'd definitely like to see happen. If you'd like to assist with this effort, please have a look at the `webpack` branch... give the `web` target a shot and let me know how it works - I haven't had a chance to test it myself yet.

**Comment by onetom** [comment]
I was just trying the https://github.com/pnpm/pnpm node package manager and it was also throwing an error related to this:

```
Error: Cannot find module 'abstract-leveldown'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/onetom/github.com/trufflesuite/ganache-core/lib/database/filedown.js:2:25)
    at Module._compile (module.js:660:30)
...
```

The fix is to add `"abstract-leveldown": "2.7.2"` explicitly as a dependency.
I will submit a PR about this later.

**Comment by yahgwai** [comment]
Hey @Tristyn @benjamincburns,

Did either of you get anywhere with this?

**Comment by Tristyn** [comment]
@yahgwai I didn't investigate any further

**Comment by davidmurdoch** [comment]
I've been experimenting with this and hope to make it a priority soon.

**Comment by davidmurdoch** [comment]
done in ganache@3.0.0-internal.0
