### ISSUE TITLE
Gas price option does not work

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/ganache-core#391]
The gas price option (whether used from the CLI or the GUI) does not seem to work.  If you specify a gas price, the CLI will report that number back to you as the gas price in the initial startup text; however, it does not then seem to actually use this number.  Transaction receipts will still show the default gas price of 20 Gwei, and the `GASPRICE` opcode will still yield a value of 2*10^10 during contract execution.

Strictly speaking, it is possible that the gas price is being set correctly, and it's just that Ganache misreports it in transaction receipts and the `GASPRICE` opcode.  However, in that case, that should be fixed.  (I'm sure it's possible to distinguish between these two scenarios, but I haven't tried.)

## Expected Behavior

Setting a gas price, whether at the CLI or GUI, should set that gas price, and that gas price should be reflected in transaction receipts, as well as in contract execution via the `GASPRICE` opcode.

## Current Behavior

Described above; the CLI will echo the given gas price back to you, but receipts and `GASPRICE` act as if the default 20 Gwei is being used.

## Steps to Reproduce (for bugs)

1. Start ganache-cli with a gas price other than the default, or start a Ganache workspace with gas price other than the default.
2. Execute any transaction (ideally one using the `GASPRICE` opcode, e.g. one that uses Solidity's `tx.gasprice` variable).
3. Get the transaction receipt and observe that it still shows a price of 20 Gwei.
4. If you executed a transaction that uses the `GASPRICE` opcode -- say by emitting the result in an event or storing it in a state variable -- inspect the event or state variable and observe that it contains a value of 2\*10^10, not whatever gas price you entered.  Alternatively, if you only stored it in a local variable, debug the transaction with Truffle Debugger and observe that the local variable gets a value of 2\*10^10.

(FWIW, the project I tested this with is the `global-test` project in the `solidity-test-cases` repository.)

## Your Environment

* Version used: Ganache CLI v6.4.1 (ganache-core: 2.5.3)
* Operating System and version: Linux Mint 18.3

**Comment by davidmurdoch** [comment]
Thanks @haltman-at. Closing this as Ganache is respecting the `gasPrice` Truffle is setting on its transactions. Issue opened at Truffle to discussing this behavior here: https://github.com/trufflesuite/truffle/issues/2221
