### ISSUE TITLE
How to launch it from sources?

### ISSUE THREAD

**Issue by askucher** [trufflesuite/ganache-core#392]
Hey guys. It starts from bundle but I expect normalized js structure here 

https://github.com/trufflesuite/ganache-core/blob/develop/index.js#L30

 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by davidmurdoch** [comment]
@askucher, what is your system environment?
