### ISSUE TITLE
Method eth_pendingTransactions is missing

### ISSUE THREAD

**Issue by princesinha19** [trufflesuite/ganache-core#405]
## Description
Method eth_pendingTransactions is not supported by ganache-cli. I think it should be added to the ganache-cli.

 `{"message":"Method eth_pendingTransactions not supported.","code":-32000,"data":{"stack":"Error: Method eth_pendingTransactions not supported.`

## Expected Behavior
Method eth_pendingTransactions should support as Geth supports it.

## Current Behavior
Method eth_pendingTransactions not supported.

## Possible Solution
need to add eth_pendingTransactions() RPC method in the code.

#### Logs

> Error: Node error: {"message":"Method eth_pendingTransactions not supported.","code":-32000,"data":{"stack":"Error: Method eth_pendingTransactions not supported.\n    at u.handleRequest (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:374907)\n    at t (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:238999)\n    at a.handleRequest (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:373894)\n    at t (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:238999)\n    at s.f.handleRequest (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:367024)\n    at s.handleRequest (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:364850)\n    at t (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:238999)\n    at c.handleRequest (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:372908)\n    at t (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:238999)\n    at a.handleRequest (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:372355)\n    at t (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:238999)\n    at d._handleAsync (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:239035)\n    at Timeout._onTimeout (/home/prince/.nvm/versions/node/v10.13.0/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:238460)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)","name":"Error"}}

## Your Environment
* Version used: Ganache CLI v6.3.0 (ganache-core: 2.4.0)
* Version of Truffle/Remix/Other tools used: Truffle v5.0.10 (core: 5.0.10)
* NodeJS Version: v10.13.0
* Operating System and version (include distro if Linux): Linux (Ubuntu)

**Comment by princesinha19** [comment]
@davidmurdoch any updates in this. As in web3.js we have added this pendingTransactions method. So, it will be good if you guys can add support for pendingTransactions asap. It is already supported by Geth and Parity.

**Comment by Exef** [comment]
Hey, @davidmurdoch I would like to start working on this issue :)

**Comment by davidmurdoch** [comment]
@Exef, @princesinha19, since `eth_pendingTransactions` appears to be deprecated we'll be closing this in favor of adding the methods introduced by geth's `txpool` namespace.
