### ISSUE TITLE
update modules / security

### ISSUE THREAD

**Issue by subtly** [trufflesuite/ganache-core#422]
related: #416 

Please update web3 module to ensure vulnerable dependency isn't installed.

## Expected Behavior
Shouldn't install vulnerable dependency.

## Possible Solution
update web3 to 1.0.0-beta.53

## Steps to Reproduce (for bugs)
yarn add <anything that depends on ganache-core>

```
warning ganache-core > web3 > web3-bzz > swarm-js > tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
```

**Comment by davidmurdoch** [comment]
Closing as web3@1.0.0-beta.37 will be released as the canonical v1 (web3@latest) in the near future. We also plan to remove web3 as a dependency in Ganache soon.
