### ISSUE TITLE
Import fails on MacOS with Node 12

### ISSUE THREAD

**Issue by markspanbroek** [trufflesuite/ganache-core#425]
I'm unable to use ganache-core on MacOS with Node 12. I seem to have hit a combination of #297 (optional depencency on scrypt is not so optional) and https://github.com/barrysteyn/node-scrypt/issues/192 (scrypt doesn't and will never work on MacOS and Node 12).

## Expected Behavior
When I import ganache-core, I expect no errors.

## Current Behavior
I see the following error:
```
Error: Cannot find module 'scrypt'
Require stack:
- /Users/mark/Development/ganache-core/node_modules/web3-eth-accounts/node_modules/scrypt.js/node.js
- /Users/mark/Development/ganache-core/node_modules/web3-eth-accounts/src/index.js
- /Users/mark/Development/ganache-core/node_modules/web3-eth/src/index.js
- /Users/mark/Development/ganache-core/build/ganache.core.node.js
- /Users/mark/Development/ganache-core/index.js
etc..
```

## Possible Solution
Updating ethereumjs-wallet and web3 to the latest versions should remove the dependency on scrypt.

## Steps to Reproduce (for bugs)
Luckily the problem also manifests itself when running the unit tests of ganache-core, so the steps to reproduce are simple:

1. Checkout ganache-core on a Mac with Node 12
2. `yarn`
3. `yarn build`
4. `yarn test`

## Context
I use ganache-core as a web3 provider in Truffle for testing.

## Your Environment
* Version used: latest develop (cba166610008262266a60908d7ab4eb20fd856be)
* Environment name and version: Node 12.1.0
* Operating System and version: MacOS Mojave
* Link to your project: https://github.com/sustainablesource/sustainablesource

**Comment by davidmurdoch** [comment]
Thanks for this! These abandoned native transitive deps have been quite the headache for many projects here at Truffle!

**Comment by adrianmcli** [comment]
@markspanbroek Are you sure that upgrading `ethereumjs-wallet` to the latest version will remove the dependency on Scrypt? Because I see that they still list Scrypt.js as a dependency: https://github.com/ethereumjs/ethereumjs-wallet/blob/master/package.json#L46

**Comment by markspanbroek** [comment]
@adrianmcli that's it exactly. Updating to scrypt.js 0.3.0 marks the native scrypt dependency as optional. With Node 12.1.0 the native scrypt doesn't compile, but as long as it's optional that doesn't matter.

**Comment by adrianmcli** [comment]
@markspanbroek noted, I'll bring this up to the team and hopefully @davidmurdoch can prioritize this.

**Comment by nicholasjpaterno** [comment]
@markspanbroek This should be fixed in ganache-core v2.5.7 although it was absent from the release notes (fixed now).  Can you test it out and reopen this issue if it still doesn't work?

**Comment by markspanbroek** [comment]
Thanks! Works like a charm.

**Comment by liamzebedee** [comment]
Still getting errors on `ganache-cli`, since it has a devDep on `"scrypt": "6.0.3",`. Ideas?

**Comment by davidmurdoch** [comment]
@liamzebedee, we don't currently _develop_ ganache-core or ganache-cli using node 12 currently. If you want to work on ganache-cli or ganache-core itself use node v10 or v8. Otehrwise `npm install ganache-cli@latest -g` or `npm install ganache-core@latest` shouldn't fail on node 12 though.

**Comment by liamzebedee** [comment]
@davidmurdoch ganache-cli still has a devDependency on `scrypt`, so it doesn't work with node 12 unfortunately.

**Comment by davidmurdoch** [comment]
@liamzebedee. Yes, but because it is a `devDependency` it won't be installed when you run `npm install ganache-cli -g`. Are you experiencing otherwise?

**Comment by cruzdanilo** [comment]
the latest version of `ethereumjs-wallet` fixes this problem.
