### ISSUE TITLE
Update ethereumjs-util to v6

### ISSUE THREAD

**Issue by frangio** [trufflesuite/ganache-core#427]
The latest `ethereumjs-util` release is 6.1.0 and Ganache is still using 5.2.0.

I'm asking for this mainly because of this change that was introduced in [6.0.0](https://github.com/ethereumjs/ethereumjs-util/releases/tag/v6.0.0):
> [BREAKING] Fixed signature to comply with Geth and Parity in toRpcSig() changing
v from 0/1 to 27/28, this changes the resulting signature buffer

To protect devs from signature malleability OpenZeppelin has restricted the accepted signatures to those with `v` in range 27/28, thus Ganache generated signatures are not validating. See https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1622.

**Comment by frangio** [comment]
The specific change needed is in the `utils.toRpcSig` function used only here:

https://github.com/trufflesuite/ganache-core/blob/cba166610008262266a60908d7ab4eb20fd856be/lib/statemanager.js#L449

As an alternative fix, if updating this dependency is too much work at the moment, maybe we can just copy the new function and use it?

https://github.com/ethereumjs/ethereumjs-util/blob/599ba5b1c7043a7e155e6032c50d7a01fc63aaf1/src/signature.ts#L52-L64

**Comment by alcuadrado** [comment]
Hey @nicholasjpaterno! I've been following this issue as I'm one of the maintainers of ethereumjs. 

My understanding is that [the comment you linked](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1622#issuecomment-504817043) is based on a misinterpretation of an internal change of Geth that shouldn't affect its users. Péter from the Geth team gave a nice explanation about this change [here](https://github.com/ethereum/go-ethereum/issues/19751#issuecomment-504900739).

Let me know if you have trouble updating any of the ethereumjs libraries. I'm happy to help.

**Comment by davidmurdoch** [comment]
Thanks, @alcuadrado. In order to not introduce a breaking change at this time I'm considering updating our usage of `toRpcSig` so it still generates the same output as it did previously (`0`/`1` instead of `27`/`28`). We only use `toRpcSig` in `eth_sign`.

What are your thoughts on Ganache keeping the 0/1 encoding (instead of 27/28) around for a bit longer?

**Comment by alcuadrado** [comment]
I understand that it's a breaking change, so it should be introduced in your next major release. This behavior has been present for so long that changing it in a minor version will probably break too many things. I'm not 100% sure about this, as anyone dealing with signatures today already has code in place to somehow normalize them.

In my experience, this has always been a source of frustration when signing using Ganache or previous versions of ethereumjs-util. Until recently, using `eth_sign` wasn't that common though, but I believe that with the increased use of meta-transactions much more developers will encounter this problem. For this reason, I think that the sooner this change can be introduced, the better.

As a data point, I just confirmed with @frangio that OpenZeppelin's signature verification library [only accepts `27`/`28`](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/136710cdd4a7b10e93b1774f086a89133f719ebe/contracts/cryptography/ECDSA.sol#L61), and it [will be used in the Gas Station Network](https://github.com/tabookey/tabookey-gasless/blob/2f31b0d72461f543398e086784150fe9b21943de/contracts/RelayHub.sol#L210). Keeping `0`/`1` will lead to complications when testing projects that make use of either of them.

**Comment by davidmurdoch** [comment]
Closed by https://github.com/trufflesuite/ganache-core/pull/445. Major version bump plan to handle the breaking change can be tracked here: https://github.com/trufflesuite/ganache-core/issues/451
