### ISSUE TITLE
BUG: not possible to delete storage on forked chain

### ISSUE THREAD

**Issue by thegostep** [trufflesuite/ganache-core#434]
See: https://github.com/trufflesuite/ganache-cli/issues/653

**Comment by davidmurdoch** [comment]
Closing in favor of #436

**Comment by niklasb** [comment]
@davidmurdoch this is an entirely unrelated issue from #436. Also see my analysis in https://github.com/trufflesuite/ganache-cli/issues/653

**Comment by davidmurdoch** [comment]
Thanks @niklasb. I've left #653 open, so in any case, this is a duplicate. I'll move 653 to the `ganache-core` repo.
