### ISSUE TITLE
Gas Estimation: tests dont work with ganache-cli@6.4.2 and later

### ISSUE THREAD

**Issue by shanefontaine** [trufflesuite/ganache-core#440]
Running any version of ganache-cli >=6.4.2 (Gas Exactimation) breaks tests on [this](https://github.com/propsproject/props-token-distribution/tree/feature/rewards-contracts) repository. In reviewing the [ganache-cli@6.4.2 changelog](https://github.com/trufflesuite/ganache-cli/releases/tag/v6.4.2), I read to submit an issue here if an OOG error is experienced.

## Expected Behavior
By following the ["Test" section of the README](https://github.com/propsproject/props-token-distribution/blob/feature/rewards-contracts/README.md), I expect all tests to run successfully (with `npm run test`). This is what happens prior to ganache-cli@6.4.2.

To run `ganache-cli`, I am not using the npm script, but rather using `ganache-cli -p 8545 -m "asset member awake bring mosquito lab sustain muscle elephant equip someone obvious" -a 100`

## Current Behavior
`error=Error: Returned error: VM Exception while processing transaction: out of gas`

`ganache-cli` versions 6.4.2, 6.4.3, and 6.4.4 produce the above error when running `npm run test`. 

## Steps to Reproduce (for bugs)
```
# Install Ganache-cli globally:
npm install --global ganache-cli

# Install Truffle globally:
npm install --global truffle@v4.1.12

# Install local node dependencies:
npm install

# Compile contracts
npm run compile

# Run ganache-cli
ganache-cli -p 8545 -m "asset member awake bring mosquito lab sustain muscle elephant equip someone obvious" -a 100

# Run contracts test suite
npm run test
```

## Context
This was discovered when running tests on this repository.

## Your Environment
* truffle@4.1.12
* solc@0.5.5+commit.47a71e8f.Darwin.appleclang

**Comment by davidmurdoch** [comment]
Hey there @shanefontaine! Thanks for opening this issue!

I _just_ released a new beta with a gas estimation fix a few minutes ago! I haven't even published the release notes yet!

Do you mind trying it out and letting me know if it fix the issue for you?

To update to the beta run:
`npm install --global ganache-cli@beta`

**Comment by shanefontaine** [comment]
Great timing. This beta version works perfectly. I'll go ahead and close this issue.

**Comment by shanefontaine** [comment]
@davidmurdoch is there going to be any note or warning on 6.4.2-6.4.4 that says that there may have been a breaking change in these versions? Or will this fix be included in a major semantic change soon? I am wondering if there are any other people that have run into this issue and have not read the one line in the Changelog.

**Comment by davidmurdoch** [comment]
This wasn't a breaking change (at least not in the semver definition of "breaking"). This was a regression/bug. The next patch release will fix this bug.

**Comment by shanefontaine** [comment]
That makes sense. Thank you.
