### ISSUE TITLE
`eth_chainId` should be configurable in cli, core, and UI

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache-core#441]
`eth_chainId` is currently hard-coded to `1337` by https://github.com/trufflesuite/ganache-core/pull/419. We should allow the developer to emulate any chain id they want. `1337` should remain the default chain_id.

**Comment by nicholasjpaterno** [comment]
Recent updates to ethereumjs-tx may help facilitate this! https://github.com/ethereumjs/ethereumjs-tx/blob/master/examples/custom-chain-tx.ts
