### ISSUE TITLE
TypeScript project fails to build; module 'web3/providers' not found

### ISSUE THREAD

**Issue by hrharder** [trufflesuite/ganache-core#465]
As of a few days ago, a TypeScript project I am working on suddenly started failing, reporting an issue originating from `node_modules/ganache-core/typings/index.d.ts` (see full error below). 

The issue appears to be the `typings/index.d.ts` file imports some types from package `web3/providers`, which really should just be `web`. This PR addresses that. I was able to confirm the change solves my problem

## Expected Behavior
The project should build with no error. 

## Current Behavior
The project fails to build with `tsc` with the following error:
```
$ tsc
node_modules/ganache-core/typings/index.d.ts:2:44 - error TS2307: Cannot find module 'web3/providers'.

2   import { Provider as Web3Provider } from "web3/providers";
                                             ~~~~~~~~~~~~~~~~
Found 1 error.
```

### Before
```typescript
// from typings/index.d.ts

declare module "ganache-core" {
  import { Provider as Web3Provider } from "web3/providers";

  namespace Ganache {
    export interface IProviderOptions {
// ...
```
### After
```typescript
// from typings/index.d.ts

declare module "ganache-core" {
  import { Provider as Web3Provider } from "web3";

  namespace Ganache {
    export interface IProviderOptions {
// ...
```
## Steps to Reproduce (for bugs)

1. Clone [this project.](https://github.com/hrharder/0x-test-project)
2. Run `yarn` to install dependencies (of which `ganache-core` is one)
3. Run `yarn build` to build the TypeScript source
4. See the error above

## Context
Our project fails to build locally and in CI environments, prohibiting us from continuing to integrate changes into our codebase.

## Your Environment

* Version used: `2.7.0`
* Environment name and version:
  - Node.js LTS (10.15.3)
  - TypeScript (`3.5.3`)
  - Yarn (`1.17.3`)
* Operating System and version:
  - MacOS (darwin)
  - Linux
* Link to your project:
  - Private project
  - [This project]() isolates the issue.

**Comment by hrharder** [comment]
Alright I have found a solution. It appears these types refer to `@types/web3` rather than the types provided by the `web3` package.

I will close this issue, but I would suggest making the change I suggested, and removing the dependency on `@types/web3`, now that the `web3` package includes TypeScript types by default.

**Comment by alcuadrado** [comment]
Hey @davidmurdoch 

This issue reappeared with the latest release of `web3`, as it now has TS types again. `web3`'s built-in types win over `@types/web3`, and they don't have a `providers`  module. 

This is preventing me from compiling one of my projects, and I couldn't find a workaround so far. I think I could delete `typings/index.d.ts` in a post-install script, but that would only work for me, and not my users.

**Comment by bigspider** [comment]
Any update? Having this problem as well.

**Comment by fabioberger** [comment]
Bump on this.

**Comment by alcuadrado** [comment]
Hey @davidmurdoch @gnidan 

I bumped into this issue once again, but this time I can't find a way to workaround it.

Have you considered just removing `types` from the `package.json`? TBH I think web3 should also do the same.

I know that removing the `types` can sound like a drastic measure, but I'm not sure who is actually using that, as it's broken. The only way to use `ganache-core` from a TS project is with `require("ganache-core")`, which ignores them. But you can't control if your dependencies use `import` or `require`.

I wouldn't delete the typings folder though, so if someone really wants to use those typings, they can do it by adding them to their `tsconfig.json`'s `files`.

Thanks!

**Comment by alcuadrado** [comment]
> I'm not sure who is actually using these typings, as they are broken

I just realized that they are only broken if you also have a `web3` installation. So maybe that's why not everyone is complaining about this.

**Comment by alcuadrado** [comment]
Update: I found a workaround. If I don't install `web3` and install `@types/web3@1.0.19` I can compile my project. 

@fabioberger this may help you

**Comment by feuGeneA** [comment]
I too am hitting this problem.  Suggested workaround (from @alcuadrado ) doesn't work for me because I also depend on `web3`.  This is the hack I've put in place to unblock myself:

#### package.json
```json
{
    "scripts": {
        "install": "sed -ie 's!import { Provider as Web3Provider } from \"web3/providers\";!import { Web3EthereumProvider as Web3Provider } from \"web3-providers\";!' node_modules/ganache-core/typings/index.d.ts"
    }
}
```

**Comment by feuGeneA** [comment]
Any update on this?  This has become a notorious issue that several people on my team have independently run into, with no known workaround better than my brutish hack.

**Comment by sushrest** [comment]
This worked for me 

**Possible Solution**
_Before_
```
// from typings/index.d.ts

declare module "ganache-core" {
  import { Provider as Web3Provider } from "web3/providers";

  namespace Ganache {
    export interface IProviderOptions {
// ...
```
_After_
```
// from typings/index.d.ts

declare module "ganache-core" {
   import * as Web3Provider from "web3";

  namespace Ganache {
    export interface IProviderOptions {
// ...
```

**Comment by davidmurdoch** [comment]
Hey all, if you've fixed this please feel free to open a PR and I'll merge it in ASAP!

**Comment by sushrest** [comment]
> Hey all, if you've fixed this please feel free to open a PR and I'll merge it in ASAP! I'll be able to work through the backlog of issues very soon!
> 
> Edit: looks like I've already got a PR here: #547 I'll see if I can get this in the next update. Sorry for the long wait on this!

@davidmurdoch the PR #547 still outputs following error:
`node_modules/ganache-core/typings/index.d.ts(3,12): error TS2305: Module '"web3"' has no exported member 'Provider'.`

The fix was importing as `import * as Web3Provider from "web3";`

I have a PR [#567](https://github.com/trufflesuite/ganache-core/pull/567) with the fix.

**Comment by adrianmcli** [comment]
I had this same error too, but I fixed it by limiting my project's `tsconfig` to only compile things in my `src` folder and it went away.

Maybe my bug is not the same as you guys, but I figured someone might google this and want to try this out.

```json
// tsconfig.json
{
  "include" :["src/**/*.ts"],
  "compilerOptions": {
    ...
}
```

**Comment by MoMannn** [comment]
+1

**Comment by tcoulter** [comment]
Just ran into this issue as well. Installing `ganache@beta` fixed this for me.

**Comment by davidmurdoch** [comment]
Closing, fixed by https://github.com/trufflesuite/ganache-core/commit/2f81da29cd13ad56b6464e0c61198538d12d7e20
