### ISSUE TITLE
Performance of --fork could be improved with memoization

### ISSUE THREAD

**Issue by area** [trufflesuite/ganache-core#471]
## Expected Behavior
When forking a provider, `ganache-core` should only have to query the provider once for the code/nonce/balance that exists at a particular address at the `safeBlockNumber`. As the response will not change, any repeated lookups should be cached.

## Current Behavior
Even if `ganache` has queried the code/nonce/balance at a particular address and block number before, it will query the provider again despite the fact this will not have changed

## Possible Solution
Memoize the calls to the fallback provider, as I have done [here](https://github.com/area/ganache-core/commit/e221818e16402e7b5aaaa10e50933e4b639d7a30), for example.

## Context
While testing upgrades for our dapp, we wish to fork mainnet to test against the current state, but we see a large number of repeated calls to `infura` when we open our dapp and browse around against our forked `ganache-cli` - not good for them, or our API limits!

**Comment by davidmurdoch** [comment]
Ah, nice. This looks great! I'm assuming this works because forking always passes a `blockNumber` and never a `tag` like `"latest"`?

If you want to write some tests for these memoized methods I'd love to pull this in!

**Comment by area** [comment]
I think this has effectively been done in #581 and can be closed.
