### ISSUE TITLE
Use new network ID for forked chain

### ISSUE THREAD

**Issue by kumavis** [trufflesuite/ganache-core#473]
Metamask uses the network id to determine what tx history to show.
I think it makes the most sense to show a new network id to indicate modeling a separate chain (that has been seeded with existing data).

this does not affect on-chain behavior.

a user could always override the network id to be the same as the original, if desired

relevant issue in metamask:
https://github.com/MetaMask/metamask-plugin/issues/783

**Comment by seesemichaelj** [comment]
@davidmurdoch, this is a pretty old issue. My personal preference is to leave things unchanged, but I want to say I've recently had issues with MetaMask with a `networkId` of `1` for a forked ganache. I feel like regardless of the default option, we should still fix this issue as I believe there's a strong use case for setting ganache's network ID to `1`. In other words, if we changed the default, users would still want to set it to 1 and we'd still have to handle the issues

I'm preferring closing this issue in favor of some more exhaustive testing of the state of things today and creating new issues for anything we find in recent versions of tools

Thoughts?

**Comment by davidmurdoch** [comment]
@tcoulter since you are considering taking on the forking port for the next breaking change release, do you want to revisit the idea of changing the default `net_version`?

**Comment by davidmurdoch** [comment]
Closing this one as we've decided the current behavior is the desired behavior.
