### ISSUE TITLE
Ganache --fork flag behaves strangely without Infura Project ID

### ISSUE THREAD

**Issue by mds1** [trufflesuite/ganache-core#476]
- [x] I asked about this on [gitter](https://gitter.im/ConsenSys/truffle) and [Spectrum](https://spectrum.chat/trufflesuite/ganache?tab=posts). [Gitter link](https://gitter.im/ConsenSys/truffle?at=5d61487038f9c27238c69444), [Spectrum link](https://spectrum.chat/trufflesuite/ganache/ganache-fork-flag-seems-to-be-buggy~07c3c8ed-8ce2-4859-8c62-a8495a4c17af)

## Expected Behavior

Ganache-cli should alert the user of potential problems that can arise when forking the mainnet via the command `ganache-cli -d -f https://mainnet.infura.io` (details on these issues are below). Either:

1. Require the user to include their full Infura URL, e.g. `https://mainnet.infura.io/v3/InfuraProjectId`, and disallow using the `--fork` option with only `https://mainnet.infura.io` (and similar for testnets), or
2. Alert the user that when using `https://mainnet.infura.io` some function calls may fail for unknown reasons (possible cause in the "Possible Solutions" section), or
3. Investigate the cause so the Infura Project ID is no longer needed (seems unlikely since this is an Infura choice)

## Current Behavior

Weird things happen when using `https://mainnet.infura.io` as the fork URL, and it's not clear why. A few things I've experienced:

- When calling Compound's `mint()` function from my contract, I receive the unhelpful `VM Exception while processing transaction: revert` error. However, deploying the contract and running the function on the real mainnet succeeded. My guess is this is not unique to Compound, but instead true for any state-changing function.
- Received the error messages below. This happened often, and the solution to these was to restart the ganache-cli node (well, the real solution was to use the right URL but I didn't know that at the time)

```
Error: Error: Error: while migrating Migrations: Returned error: VM Exception while processing transaction: Error: Returned error: legacy access request rate exceeded
    at Object.run (/Users/username/.nvm/versions/node/v10.16.0/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.32 (core: 5.0.32)
Node v10.16.0
```

```
Error: Error: Error: while migrating Migrations: Returned error: Returned error: project ID is required to access archive state
    at Object.run (/Users/username/.nvm/versions/node/v10.16.0/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.32 (core: 5.0.32)
Node v10.16.0
```

## Possible Solution

I'm not entirely sure if this is true, but it seems the cause is that Infura will let you read the state without the Project ID in the URL, but will not let you make any state changes. This can't be entirely true since calling `approve()` on an ERC20 contract succeeded

Regardless, either of the first two options listed in the Expected Behavior would be useful. Currently, it's unclear that the source of all the above issues is from not including the full Infura URL. 

## Steps to Reproduce (for bugs)

We'll use an Example that uses DAI and Compound's cDAI here, since that's how I discovered this.

Create a contract like the one below

```javascript
pragma solidity ^0.5.10;

// Define standard ERC20 interface with the addition of the `mint()` function
interface ICERC20 {
    function totalSupply() external view returns (uint256);
    function balanceOf(address account) external view returns (uint256);
    function transfer(address recipient, uint256 amount) external returns (bool);
    function allowance(address owner, address spender) external view returns (uint256);
    function approve(address spender, uint256 amount) external returns (bool);
    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);
    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
    function mint(uint mintAmount) external returns (uint);
}

contract TestContract {
  // NOTE: These are the mainnet addresses
  address daiAddress = 0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359;
  address cdaiAddress = 0xF5DCe57282A584D2746FaF1593d3121Fcac444dC;
  ICERC20 dai = ICERC20(daiAddress);
  ICERC20 cdai = ICERC20(cdaiAddress);

  constructor() public {
    // Approve the cDAI contract to spend our DAI balance
    bool daiApprovalResult = dai.approve(cdaiAddress, 2**256-1);
    require(daiApprovalResult, "Failed to approve cDAI contract to spend DAI");
  }

  function deposit() public {
    uint _daiBalance = dai.balanceOf(address(this));
    assert(cdai.mint(_daiBalance) == 0); // this line is where the transaction reverts
  }
}
```

Next, start ganache-cli using `ganache-cli -d -f https://mainnet.infura.io`.

Write a test which sends DAI from an arbitrary account holding DAI (make sure to unlock this account when starting ganache) to the contract, then calls the `deposit()` function. Running this test should error with `VM Exception while processing transaction: revert`.  

The other error messages should eventually show up if you leave the node running and re-run tests a few times.

## Context

There was a few different, seemingly unrelated problems being experienced, and it wasn't clear that the underlying cause of them all was something so simple. Would have saved lots of debugging time with a warning message about a missing project ID

## Your Environment
* Version used: Ganache CLI v6.6.0 (ganache-core: 2.7.0)
* Version of Truffle/Remix/Other tools used: Truffle v5.0.32
* NodeJS Version: 10.16.0
* Operating System and version (include distro if Linux): macOS 10.14.5
* I intend to submit a pull request to fix this issue: [ ]

**Comment by rnbrady** [comment]
Could it be rate-limiting? 

From the [Infura docs](https://infura.io/docs/ethereum/json-rpc/ratelimits):

> Make sure you are using a Project ID in your URL. Requests without a Project ID will be severely rate-limited or even outright blocked.

**Comment by seesemichaelj** [comment]
This seems to no longer be an issue due to more strict handling on Infura's part. Starting up ganache without a project ID immediately returns the error:

```
$ ganache-cli --fork https://mainnet.infura.io
Ganache CLI v6.10.1 (ganache-core: 2.11.2)
Error: Returned error: project ID is required
    at Object.ErrorResponse (/home/mike/.nvm/versions/node/v12.18.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:39:2207407)
    at /home/mike/.nvm/versions/node/v12.18.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:39:2206279
    at /home/mike/.nvm/versions/node/v12.18.3/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:39:2193803
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

However, ganache-cli doesn't seem to close during initialization, but this error would be widely prevalent. After discussing with @davidmurdoch, it's not worth fixing the startup failing cases due to the new TS refactor handling it better.

However, I'm going to wrap the error to say it's related to initialization
