### ISSUE TITLE
VM Revert Reasons not returned 

### ISSUE THREAD

**Issue by BrendanChou** [trufflesuite/ganache-core#480]
Revert reasons are not being passed back by ganache-core anymore

## Expected Behavior
Old error.message (v6.4.1)
`Returned error: VM Exception while processing transaction: revert ${solidityRevertReason}`

## Current Behavior
error.message being passed back (v6.7.0-beta.0)
`error: execution error: revert`

## Steps to Reproduce (for bugs)
Send a transaction that reverts with a solidity revert string.

## Your Environment
    "truffle": "5.0.34",
    "ganache-cli": "6.7.0-beta.0",

**Comment by BrendanChou** [comment]
This seems to be a problem in estimate gas. Investigating further

**Comment by davidmurdoch** [comment]
Previously, estimate gas was _incorrectly_ returning estimates for failing transactions instead of failing (like other clients do). We'll look into providing the revert reason string to the error message in estimate gas. /cc @nicholasjpaterno

**Comment by Kuzirashi** [comment]
Is there a plan to release #502 any soon?

cc @davidmurdoch
