### ISSUE TITLE
Installation errors with npm using node v12

### ISSUE THREAD

**Issue by bigspider** [trufflesuite/ganache-core#489]
Installing `ganache-core` with `npm` completes with errors when ran on Node v12; after that, `npm ci` aborts.

## Expected Behavior
`npm install ganache-core` should complete without errors.

## Current Behavior
`npm install ganache-core` has errors; `npm ci` after installing fails.

## Steps to Reproduce (for bugs)

1. `mkdir test && cd test`
2. `nvm install v12.11.0` (or any other v12.x)
3. `npm install ganache-core`

Installation completes, but with errors, like:

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/spider/.nvm/versions/node/v12.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-64-generic
gyp ERR! command "/home/spider/.nvm/versions/node/v12.11.0/bin/node" "/home/spider/.nvm/versions/node/v12.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/spider/temp/test/node_modules/ganache-core/node_modules/keccak
gyp ERR! node -v v12.11.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/spider/.npm/_logs/2019-09-30T10_13_36_557Z-debug.log
```
and
```
make: Leaving directory '/home/spider/temp/test/node_modules/ganache-core/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/spider/.nvm/versions/node/v12.11.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-64-generic
gyp ERR! command "/home/spider/.nvm/versions/node/v12.11.0/bin/node" "/home/spider/.nvm/versions/node/v12.11.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/spider/temp/test/node_modules/ganache-core/node_modules/scrypt
gyp ERR! node -v v12.11.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
```

After that, `npm ci` aborts because of the same errors.

## Context
We are not able to use `npm ci` without downgrading Node to version 11.

## Your Environment
* Version used: ganache-core 2.8.0 (also tried on 2.7.0)
* Operating System and version:Ubuntu 18.04 LTS / Linux kernel 4.15.0-64
* Link to your project: [PISAresearch/pisa](https://github.com/PISAresearch/pisa)

**Comment by davidmurdoch** [comment]
Thanks @bigspider for opening this issue. These errors are expected on Node 12, as both scrypt and keccak have pure js fallbacks that are used if the native components can't be built. Are you sure npm ci is aborting? I'm unable to reproduce the abort locally.

**Comment by bigspider** [comment]
Thanks @davidmurdoch for the quick reply. Indeed, I assumed `npm ci` was aborting as its output ends with the errors, unlike `npm install`; but I checked the exit status code and it is 0, so it shouldn't affect our flow.

Still, the errors are annoying in the logs and it would be nice to fix them - leaving it up to you if this issue should be closed or not.

**Comment by davidmurdoch** [comment]
Node 8 and Node 10 get a significant performance boost for some methods by using these native modules, so removing them from the library (which would be very difficult as they are deep dependents of many of our direct dependencies) would result in a performance regression. These two native libraries will not be updated to support Node 12, so unfortunately we're stuck with them for now.
