### ISSUE TITLE
Ganache 1.0.2 stays frozen on the loading screen

### ISSUE THREAD

**Issue by elie222** [trufflesuite/ganache-core#50]
Ganache 1.0.1 worked fine for me. I just updated and it no longer works. I just see the brown screen with the Ganache logo and v1.0.2.

**Comment by elie222** [comment]
I am referring to the desktop app (on latest version of Mac OS X).

**Comment by benjamincburns** [comment]
Hi @elie222 - this shouldn't be the case as of Ganache v1.1.0.

Also in the future, please report bugs specific to the Ganache UI at the [ganache repo's issue page](https://github.com/trufflesuite/ganache/issues).

**Comment by pedroduartecosta** [comment]
For anyone who may run into this in the future. My problem was that I was **loading a truffle.js config** file and it was getting stuck on the loading screen.

Running `npm install` inside my project folder, where the truffle.js file is, **fixed** the problem.
