### ISSUE TITLE
estimategas throws uncatchable exception

### ISSUE THREAD

**Issue by sirpy** [trufflesuite/ganache-core#506]
happens on ganache 6.7.0
downgrading to 6.6.0 solves the issue
found that the issue happens if in web3js constructor i pass defaults with
defaultGas: 140000,
removing it also solves the issue on 6.7.0

**Comment by nicholasjpaterno** [comment]
@sirpy we've changed some things with mining, can you confirm that this is still an issue on `ganache-core@latest`?

**Comment by sirpy** [comment]
@nicholasjpaterno 
Hey, i'm not sure what was the exact issue,
I tried upgrading to latest ganache-cli but local unit test for estimate gas fails with:
Error: Node error: {"message":"VM Exception while processing transaction: out of gas","code":-32000,"data":{"stack":"c: VM Exception while processing transaction: out of gas

on ganache 6.6.0 it works fine

**Comment by davidmurdoch** [comment]
Closing for issue maintenance. If this is still an issue after trying it with `latest` or the latest `beta` releases, please comment and I'll reopen it. Thanks!
