### ISSUE TITLE
TypeScript typings are wrong.

### ISSUE THREAD

**Issue by MicahZoltu** [trufflesuite/ganache-core#508]
https://github.com/trufflesuite/ganache-core/blob/bda6a4ae07400dc5567aa50776e4432f96d3ae1e/typings/index.d.ts#L1-L48

The TypeScript type definitions for this project appear to be incorrect.  If I do `import ganache from 'ganache-core'` my project will compile without trouble but will fail at runtime due to `ganache` being `undefined`.  However, if I instead do `import * as ganache from 'ganache-core'` or `import { server } from 'ganache-core'` I get compile-time errors but the script runs at runtime.

I believe the proper definition should look something like this instead:
```typescript
declare module 'ganache-core' {
	import { Provider as Web3Provider } from "web3/providers";
	export interface IProviderOptions {
		account_keys_path?: string;
		accounts?: object[];
		allowUnlimitedContractSize?: boolean;
		blockTime?: number;
		db_path?: string;
		debug?: boolean;
		default_balance_ether?: number;
		fork?: string | object;
		fork_block_number?: string | number;
		gasLimit?: number;
		gasPrice?: string;
		hardfork?: "byzantium" | "constantinople" | "petersburg";
		hd_path?: string;
		locked?: boolean;
		logger?: {
			log(msg: string): void;
		};
		mnemonic?: string;
		network_id?: number;
		networkId?: number;
		port?: number;
		seed?: any;
		time?: Date;
		total_accounts?: number;
		unlocked_accounts?: string[];
		verbose?: boolean;
		vmErrorsOnRPCResponse?: boolean;
		ws?: boolean;
	}

	export interface IServerOptions extends IProviderOptions {
		keepAliveTimeout?: number;
	}

	export function provider(opts?: IProviderOptions): Provider;
	export function server(opts?: IServerOptions): any;

	export interface Provider extends Web3Provider {
		close: (callback: Function) => void;
	}
}
```

Do the current typings actually work for anyone?  If so, how are you doing your imports?  If not, I can submit a PR with the above change.

**Comment by davidmurdoch** [comment]
@CruzMolina and @nicholasjpaterno created these Typings. Can either of your confirm that these typings work where you needed them?

**Comment by CruzMolina** [comment]
Hey @MicahZoltu! Based on the current typings structure, you'll have to import the Namespace (`import Ganache from "ganache-core"`) to get things working.

Here's an example where we use the typings in one of Truffle's tests: https://github.com/trufflesuite/truffle/blob/develop/packages/hdwallet-provider/test/provider.test.ts

I'm not sure on the completeness of the typings, but so far I haven't run into an issue with them.

**Comment by MicahZoltu** [comment]
The proposed solution of `import Ganache from 'ganache-core'` does not work for me.  I'm surprised that your solution works because looking at `ganache-core/index.js` it has `module.exports = require('./publicexports.js')` and `publicexports.js` has:
```
module.exports = { server, provider } // truncated for brevity
```
Note that it does not have a default export, so `import Ganache from 'ganache-core'` shouldn't work since that is a a default import.

I do notice that in `index.js` you are conditionally exporting from a bundle.  I wonder if one of us is hitting the one of the exports, and the other is hitting the other export and they are not the same?

**Comment by MicahZoltu** [comment]
### Full Repro

index.ts
```typescript
import Ganache from 'ganache-core'
Ganache.server()
```
tsconfig.json
```typescirpt
{
	"compilerOptions": {
		"target": "esnext",
		"module": "commonjs",
		"moduleResolution": "node",
	},
}
```
```
mkdir test
cd test
# --ignore-scripts to avoid running into problems with node-gyp failing to install unnecessary dependencies
npm install typescript ts-node ganache-core --ignore-scripts
npx ts-node index.ts
```
> Cannot read property 'server' of undefined

**Comment by zemse** [comment]
@MicahZoltu Can you try doing this? It worked for me.
```typescript
import ganache from 'ganache-core';

const server = ganache.server();

server.listen(8545, () => {
  console.log('server started');
});
```

**Comment by MicahZoltu** [comment]
@zemse When importing default exports the name chosen by the importer doesn't matter.  I could do the following and it would be functionally equivalent. 
```ts
import apple from 'ganache-core
apple.server()
```
Did you use the same tsconfig.json as I did above?  Were you using a newer version of ganache-core?

**Comment by zemse** [comment]
> @zemse When importing default exports the name chosen by the importer doesn't matter. I could do the following and it would be functionally equivalent.

Oh! I think I forgot this fact in my instincts. Maybe, frequently using the named export in my projects instead of default export did that to me.

> Did you use the same tsconfig.json as I did above? Were you using a newer version of ganache-core?

I am using the version `2.10.2` (installed yesterday). This is my tsconfig.json.
```typescript
{
  "include": ["src/**/*.ts"],
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "outDir": "build/",
    "rootDir": "src/",
    "downlevelIteration": true,
    "strict": true,
    // "moduleResolution": "node",
    "forceConsistentCasingInFileNames": true
  }
}
```
Can you try using this version?

**Comment by davidmurdoch** [comment]
Closing, as the typings have since been fixed. Please make a new issue if you find this is not the case for you. Thanks!

**Comment by PaulRBerg** [comment]
> Closing, as the typings have since been fixed

Have they? I'm using ganache-core@2.12.1 and all I get is `provider` and `server` in my VSCode auto-complete:

<img width="560" alt="Capture d’écran 2020-10-24 à 22 27 25" src="https://user-images.githubusercontent.com/8782666/97091916-1f172900-1648-11eb-8c12-c62f0d149ae4.png">

I'm using this [tsconfig.json][1] file.

[1]: https://github.com/MainframeHQ/mainframe-lending-protocol/blob/7f1d687fb7da8dae57186ff7de9b44aab90fbfcd/tsconfig.json

**Comment by davidmurdoch** [comment]
Yes, that's all there is at that level.

**Comment by PaulRBerg** [comment]
I see. And is there no way to import specific types like "IProviderOptions"?

**Comment by zemse** [comment]
> and all I get is provider and server in my VSCode auto-complete

I have observed that when you type next to a `:` of a var while specifying type, it gives more suggestions.

```ts
import Ganache from 'ganache-core';

const variable: Ganache. // gives more suggestions like IProviderOptions
```

Hope this helps

**Comment by davidmurdoch** [comment]
Yes, `IProviderOptions` is only type, and doesn't have a corresponding runtime component, whereas `provider` and `server` are both types AND have a runtime component (the function). When coding, TypeScript recognizes if you are writing runtime code or type code, and only gives you appropriate hints.

examples:

```typescript
// runtime
const doesntMakeSense = Ganache.IProviderOptions; // would be `undefined` since this is runtime code, a `IProviderOptions` doesn't have a runtime component

type myType = Ganache.IProviderOptions // works because this is type-level code
let myThing: Ganache.IProviderOptions = {gasPrice: 123456}; // works because this is also type-level code
```

I'm sure there is a better way of explaining it, but hopefully this helps clear things up for you.
