### ISSUE TITLE
Ganache does not check for insufficient funds when sending transactions

### ISSUE THREAD

**Issue by aacampbell** [trufflesuite/ganache-core#516]
## Expected Behavior

When sending a transaction the sender should be checked for sufficient funds as is done by other ethereum node codebases. 

## Current Behavior

When blocktime is zero, the sending of a transaction does indeed result in an error being returned of the form `sender doesn't have enough funds to send tx. The upfront cost is: xxx and the sender's account only has: yyy`. However, when blocktime is non-zero this error is not returned when sending the transaction, rather the transaction hash is returned. This makes calling code think that sending the transaction was successful, which is incorrect and in Web3 leads to an indefinite hang due to waiting for a transaction receipt that will never come.

The aforementioned error appears to originate from the underlying `ethereumjs-vm` as a result of an `evm_mine`, not as a result of validation on submission of the transaction to the "node". This explains the incorrect behaviour when blocktimes are non-zero, as the error is 'emitted' some time after the transaction is submitted/enqueued by ganache-core at the time when `evm_mine` is next called. This is shown in ganache's logs, but probably reflects a logging call rather than an actual valid callback invocation containing the error.

## Possible Solution
When sending a transaction, ganache should check that the sender's balance is equal to or greater than the upfront costs of the transaction, as is done by other node codebases.

## Steps to Reproduce (for bugs)

1. Start up ganache with a non-zero block time
2. Deploy a dummy contract from an account with zero balance

## Context
This has affected our use of ganache-core in automated testing, where we want to run our tests with zero blocktime and non-zero blocktime. We do both because zero blocktime allows quick testing of our code, while the non-zero blocktime better reflects actual production conditions. The code being tested includes scripts for users which need provide accurate feedback about why a transaction did not work. This issue means we cannot give reliable feedback.

## Your Environment

* Version used: ganache-core 2.8.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Node 10.17.0
* Server type and version: Macbook Pro 2019
* Operating System and version: Ubuntu 18.04
* Link to your project: n/a

**Comment by haltman-at** [comment]
This sounds like correct behavior; whether funds are sufficient is not checked until the node attempts to try to mine the transaction.  So I'm not certain there's an issue here.  I'm going to close this for now, but feel free to comment further if I'm mistaken or there's some other way this can be improved and we can perhaps reopen this.
