### ISSUE TITLE
Built in tracers don't seem to work

### ISSUE THREAD

**Issue by liamaharon** [trufflesuite/ganache-core#523]
## Expected Behavior
as described in https://github.com/ethereum/go-ethereum/pull/15516 when I call `debug.traceTransaction` with `{tracer: "callTracer"}` as the second argument I expect the call to return a list of internal transactions.

## Current Behavior
 I'm returned the same data as if I passed an empty object as the second parameter 

## Possible Solution
extend tracing ability to be on par with Geth. logic looks to be contained here https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/internal/tracers/call_tracer.js, but not 100% sure how it can be applied in Ganache 

## Context
I want to trace transactions that are pending and get the list of internal transactions they're likely to trigger. unfortunately Geth doesn't allow tracing a transaction until it is mined, so I want to simulate each pending transaction being mined on a Ganache instance forked from Geth and make the `debug.traceTransaction` straight afterwards.

**If somebody is willing to provide guidance I would be happy to implement this feature and open a PR**

## Your Environment

* Version used: 2.8.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Nodejs v12.13.1
* Operating System and version: Ubuntu 18.04

**Comment by liamaharon** [comment]
https://gist.github.com/liamaharon/ed9ede5eb93367e731d5ec7b795995af

converts raw `CALL`, `DELEGATECALL`, `CALLCODE` to an array of internal transactions

**Comment by cwazy2020** [comment]
I have no CALL, DELEGATECALL, or CALLCODE op’s in the traceTransaction output (from Ganache) out of dozens of txs that I have tested, all of which went to contracts.  Any idea how this could happen?

**Comment by eggplantzzz** [comment]
This is a duplicate (related issue) of https://github.com/trufflesuite/ganache-core/issues/381.
