### ISSUE TITLE
Windows Subsystem for Linux - RPC Error when sending transaction 

### ISSUE THREAD

**Issue by j-mars** [trufflesuite/ganache-core#531]
**Describe the bug**

I have a development environment setup in windows 10 using Windows Subsystem for Linux.
When I execute a send transaction using my Dapp I get the following error in the console:

MetaMask - RPC Error: Error: [ethjs-rpc] rpc error with payload {"id":283255458009,"jsonrpc":"2.0","params":["0xf8b2018504a817c8008303b5d594254dffcd3277c0b1660f6d42efbb754edababc2b82012cb84406ca6af6000000000000000000000000141f5fca84cc82ef0a6751241019471731289456af0cebd27bd02fd316270eed31448fb17177fa8d32aa861b4d9a6c7b0d163bf68602df532bcf12a077aa2b78af66efc28bd279e9398e79b58cc3c135cd611711f6016ed3035f51f1a003e5a85e095301d236e4931d8954187c454353085fe126cd70db139ef8f9ecb3"],"method":"eth_sendRawTransaction"} [object Object]

The problem is not with the Dapp as I am able to make the transactions just fine in a separate Ubuntu Virtual Box environment.
The problem seems to be related with ganache-cli (which is installed on WSL), because if I use ganache-gui, which is installed in Windows 10, everything works fine.
Metamask custom RPCs are configured with port 8545 for ganache-cli and 7545 for ganache-gui.

**To Reproduce**
Install

- WSL in Windows 10 with Ubuntu
- node lts using nvm
- latest yarn
- global ganache-cli and truffle
- build essentials

Then

- configure a dapp project in VSCode and launch it
- try to send a transaction using metamask (custom rpc - http://127.0.0.1:8545)
- verify the error I get above.

Then (to try without error)

- install ganache-gui on windows side normally
- configure your truffle-config with a second network and deploy contracts there
- configure a second custom rpc on another port (e.g 7545)
- You can send transactions normally.

**Expected behavior**

The transactions proceed without any error on ganache-cli installed and launched in WSL

**Screenshots**

![image](https://user-images.githubusercontent.com/45543880/72445398-8e9ee480-37a9-11ea-9418-cdfe4939b1fc.png)

**System details**

Windows 10 with Windows Subsystem for Linux
Metamask 7.7.2
Latest Google Chrome or Brave
Ganache-cli 6.8,1 (in WSL)
Ganache-gui 2.1.2 for Windows

**Comment by davidmurdoch** [comment]
@nicholasjpaterno and I have tracked down the issue and have the fix almost ready now. In the meantime, you can start ganache with `ganache-cli --network_id 1` and ganache will now permit the metamask signed transaction. Sorry for the headache this has caused; I hope to get a hotfix out to fix this in the morning!

**Comment by j-mars** [comment]
Okay, so changing to id 1 fixes the issue temporarily.

Thanks

**Comment by nicholasjpaterno** [comment]
Fixed in PR: https://github.com/trufflesuite/ganache-core/pull/532

You can use this now with the latest release https://github.com/trufflesuite/ganache-cli/releases
