### ISSUE TITLE
eth_sign API out of sync with ethapi

### ISSUE THREAD

**Issue by parkan** [trufflesuite/ganache-core#555]
As of https://github.com/ethereum/go-ethereum/pull/2940, eth_sign api has changed. It is now `eth_sign(address, msg)`, accepting arbitrary input and putting it through keccak256.

 

## Expected Behavior

Upstream eth_api introduced a breaking change where `eth_sign` now accepts the actual *message*, rather than a 32 byte hash digest. Signature is now `eth_sign(address, msg)`

## Current Behavior

testrpc currently emulates existing `eth_sign(address, sha3(msg))` behavior

## Possible Solution

Change `ethereumjs-util.ecsign` to call `keccak256` before calling `secp256k1.sign`

## Context

We need to sign statements with web3, which is now incompatible between testrpc and real ethapi.

## Your Environment

* Version used: v3.0.3
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): n/a
* Server type and version:
* Operating System and version: os x
* Link to your project: https://github.com/mediachain/aleph-ethereum

**Comment by eggplantzzz** [comment]
Looking at this issue, it seems like it has been updated. Can anyone here confirm that this is indeed updated and behaving correctly?

**Comment by tcoulter** [comment]
Closing this because after review, we think it's no longer an issue. Please open a new ticket if you believe this to still be a problem.
