### ISSUE TITLE
Reign in Ganache-Core dependencies.

### ISSUE THREAD

**Issue by MicahZoltu** [trufflesuite/ganache-core#563]
I just did `npm install ganache-core` and it brought in:
> added 1642 packages from 1150 contributors and audited 46082 packages in 36.351s
> found 11 vulnerabilities (10 low, 1 high)
>   run `npm audit fix` to fix them, or `npm audit` for details

1642 dependencies is *insanity* and should be reigned in.  While I understand this is a pretty big project, that is a *crazy* number of dependencies.  Also, the more dependencies you have the more vulnerabilities there will be.  Since this is a test library it isn't that big of a deal except that it contributes to training users to ignore GitHub vulnerability warnings and can potentially obscure *actual* vulnerabilities due to having to mentally ignore all of the vulnerabilities from packages brought in by ganache-core.

Also, those 1642 dependencies account for ~166 MB of disk space and bandwidth to fetch, more if you count headers (bandwidth) and block sizes (disk space).

Surely, there is room to trim down some of this cruft?

**Comment by MicahZoltu** [comment]
A bit of digging suggests that a large chunk of the problem is web3.  While I'm guessing it would be non-trivial, can Ganache switch to something more sane like `ethers`?

**Comment by davidmurdoch** [comment]
We plan on removing web3 from production in the future.

**Comment by davidmurdoch** [comment]
Not sure when we should close this. I've reduced the number of dependencies in the latest beta release to 904 (though it still includes web3). Perhaps a better metric is installation time, which for me, now installs in about 9 seconds.

**Comment by MicahZoltu** [comment]
My hope would be to get the number of dependencies down to 10s, rather than hundreds or thousands.  The only real way to achieve this would be by removing web3 though.

**Comment by davidmurdoch** [comment]
Fixed in next major release. Created new problem whilst fixing: https://github.com/trufflesuite/ganache-core/issues/744
