### ISSUE TITLE
Allow `--unlock` functionality when ganache is already running

### ISSUE THREAD

**Issue by iamdefinitelyahuman** [trufflesuite/ganache-core#588]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5ea068f0f39e5c2fbb970216

## Summary
It is possible to unlock accounts with the `--unlock` flag when launching ganache. It would be useful to be able to do this while ganache is already running.

## Context
When combined with`--fork`, `--unlock` is very powerful in that it lets the me simulate mainnet transactions from accounts I don't control. However, I like to play around in the console and so often don't know which accounts I want to unlock ahead of time. Currently each new unlock means exiting, restarting, and repeating a (sometimes lengthy) series of transactions.

## Possible Solution
I have three ideas for possible implementations:

1. Add a cli flag `--unlock-all` that arbitrarily allows transactions to be broadcast from any address, without having to explicitly unlock first. In my mind this is the best approach.
2. Add a new custom RPC endpoint that accepts an address as a single parameter, and unlocks that address.
3. Modify the behavior of [`personal_unlockAccount`](https://github.com/ethereum/go-ethereum/wiki/Management-APIs#personal_unlockAccount) so that any account may be unlocked with a passphrase of `null`. Optionally add a cli flag that enables this behavior.

**Comment by iamdefinitelyahuman** [comment]
An RPC method would work fine for me..  I see in my initial writeup I suggested a flag as the best approach, but today I feel the custom RPC method is actually better as it doesn't require me to do anything special prior to launching.

Thanks for your work on this tool btw!

**Comment by ItsNickBarry** [comment]
It would be useful to be able to simply unlock all accounts, preventing the need for RPC calls.  I can't think of a test case that would rely on an account's being locked.

**Comment by ItsNickBarry** [comment]
I now see that that's already been suggested.  In that case, I agree that `--unlock-all` would be a useful addition.

**Comment by iamdefinitelyahuman** [comment]
Implemented in #622

**Comment by surajsjain** [comment]
Is there any way I can use this with the latest version (or a different branch) of Ganache CI so that I can unlock all the accounts?
