### ISSUE TITLE
ganache consider logIndex as the position in a transaction but the spec define the logIndex as the position in the block

### ISSUE THREAD

**Issue by wighawag** [trufflesuite/ganache-core#596]
according to https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges and http://web3js.readthedocs.io/en/1.0/web3-eth.html#getpastlogs

the logIndex is "Integer of the event index position ***in the block***."

Ganache report logIndex as the position ***in the transaction***

See test case here : https://github.com/wighawag/web3-logIndex-test
and deployed contract on rinkeby : https://rinkeby.etherscan.io/verifyContract?a=0xff9e5d94dc4205fa0a7dc6905f2eb42372431b0c
look at block https://rinkeby.etherscan.io/block/2345019

to reproduce with ganache
- stop_mine
- call testEvents
- call testEvents
- mine

## Expected Behavior

get past logs from thet deployed contract:
transaction 0 :
result[0].logIndex == 0
result[1].logIndex == 1
transaction 1 :
result[2].logIndex == ***2***
result[3].logIndex == ***3***
                
## Current Behavior
transaction 0 :
result[0].logIndex == 0
result[1].logIndex == 1
transaction 1 :
result[2].logIndex == ***0***
result[3].logIndex == ***1***

You can see the full test case in : https://github.com/wighawag/web3-logIndex-test
just clone and run ```yarn && yarn test```

for rinkeby behaviour  on ifnura node see https://github.com/wighawag/web3-logIndex-test/blob/master/rinkeby.js

**Comment by davidmurdoch** [comment]
Related to https://github.com/trufflesuite/ganache-core/pull/463

**Comment by gnidan** [comment]
Thanks for reporting this! This _should_ be fixed in our upcoming v7.0.0 release, but we'll add it to the milestone for acceptance validation to make sure.

**Comment by eggplantzzz** [comment]
Do note that I ran @wighawag's tests in the repo mentioned above against new Ganache. The tests pass implying this is indeed fixed. I also ran the tests against current Ganache to ensure they failed and they did.
