### ISSUE TITLE
Ensure `ForkedBlockchainBaseTrie.prototype.del` works with snapshots

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache-core#624]
I have a feeling this may be a duplicate of #611, but I'm pulling #4 out of https://github.com/trufflesuite/ganache-core/issues/483#issuecomment-680185528

> I wonder if we can handle evm_snapshot + .del + evm_revert. 👀

**Comment by seesemichaelj** [comment]
FYI @mds1, I was mentioning a potential beta release this week. @davidmurdoch got some time to review my changes and discovered a potential regression that we need to resolve. Hopefully next week!

**Comment by mds1** [comment]
Awesome, thanks for the update. Really appreciate you squashing all these fork bugs! 🙌

**Comment by seesemichaelj** [comment]
This was released in https://github.com/trufflesuite/ganache-core/releases/tag/v2.12.2-beta.0

**Comment by seesemichaelj** [comment]
@mds1 Have the latest releases been working for you? Looks like the fixes made it into a stable release:
core: https://github.com/trufflesuite/ganache-core/releases/tag/v2.13.0
cli: https://github.com/trufflesuite/ganache-cli/releases/tag/v6.12.0

**Comment by mds1** [comment]
Yes, things have been working great so far!

**Comment by mds1** [comment]
Thanks again for pushing all these fixes through!

**Comment by seesemichaelj** [comment]
Awesome! No problem! Glad we could get these finay solved
