### ISSUE TITLE
Creating Ganache server with specified accounts (private key and balance) creates accounts with zero balance

### ISSUE THREAD

**Issue by aleybovich** [trufflesuite/ganache-core#64]
Initially found when using `ganache-cli`, I tracked it down to `ganache-core`. 
```
var options = { accounts: [{ sekretKey: <secret>, balance: <balance> }] }
var server = Ganache.server(options);
```

Accounts created this way always have zero balance even though it's specified.

UPDATE: Further testing shows that accounts are being created with 100 ETH balance when the balance is not specified; when it's specified then the accounts are created with zero balance, which is still a bug.

**Comment by benjamincburns** [comment]
Hi @aleybovich,

It looks like you've misspelled `secretKey` in your blob above. Also bear in mind that we run the OpenZeppelin test suite as part of every ganache-core release, and those tests make use of this functionality.

Be sure that you're specifying the `balance` key as a hexidecimal string, as well.

Hope this helps!
