### ISSUE TITLE
I "succeeded" to hang Ganache

### ISSUE THREAD

**Issue by vporton** [trufflesuite/ganache-core#647]
## Bug description

The software at https://github.com/vporton/eth-tokens-sum/tree/hangs-ganache consistently hangs Ganache.

## Notes

I start Ganache with `npx ganache-cli -d`, then run `npx buidler test --network ganache`.

Then after a few hundereds or so iterations of my software's loop Ganache hangs (no more reacts to queries, cannot be exited with Ctrl+C, only with Ctrl+Z and `kill`).

Note that my software uses a random number generator. To make the test fully repriseable, need to seed it with a fixed value. However, every time I ran this test, Ganache hanged.

Also note that Buidler instead produces a weird out-of-gas error. (I suspect it has a common codebase with Ganache and this is essentially the same bug.)

## Your Environment
* Version used: Ganache CLI v6.11.0 (ganache-core: 2.12.1)
* Operating System and version: Ubuntu 20.04.1

**Comment by vporton** [comment]
> @vporton did you figure out the issue?

First you were right, there was an infinite loop in my contract. Second after much debugging (just two minutes ago), my test now runs without errors.

**Comment by davidmurdoch** [comment]
Good to hear! Good luck on the bounty!
