### ISSUE TITLE
BlockchainDouble seems to be using the wrong Trie import

### ISSUE THREAD

**Issue by kfichter** [trufflesuite/ganache-core#664]
Noticed this while trying to implement `eth_getProof` on top of ganache. It seems like `BlockchainDouble` is importing `Trie` as:

https://github.com/trufflesuite/ganache-core/blob/1177fe8a2711066a1b082b15d22585158001e80d/lib/blockchain_double.js#L9

When I'd expect to see:

```
var Trie = require("merkle-patricia-tree/secure");
```

The base `Trie` class (instead of the "secure" `Trie`) spits out invalid proofs because the keys aren't hashed before insertion.

You can see this discrepancy within `ethereumjs-vm`, which indeed uses the "secure" version [here](https://github.com/ethereumjs/ethereumjs-vm/blob/c1316fc17ea10ce3d3decc6cc9e5b11962a5b079/lib/index.ts#L16). Although using the base class is technically fine, it does produce a non-standard (and incompatible) result for `eth_getProof`.

**Comment by davidmurdoch** [comment]
I _think_ this is due to the fact that we pre-seed accounts with ether on start up, and Secure trie won't allow us to start up with the Trie in this state. Though I'm not entirely positive, and if that _is_ true, I wonder if there is a simple way around it.

Have you tried swapping the Trie out for the SecureTrie then running the ganache-core tests? I'm curious  if the `eth_getBalance`-related tests in test/accounts.js break (`eth_getBalance` returns `"0x0"` when we expect a non-zero value).

**Comment by davidmurdoch** [comment]
Adding this to the 3.0 milestone release.

**Comment by davidmurdoch** [comment]
@kfichter I haven't yet researched the getProof myself, if you'd like to try adding eth_getProof in the `next` branch (which is in TypeScript) that'd be awesome! There isn't really a contributors guide yet, so it might be challenging to navigate at the moment. Let me know if you'd like to tackle it!

**Comment by davidmurdoch** [comment]
fixed in ganache@3.0.0-internal.0

**Comment by kfichter** [comment]
@davidmurdoch I'd definitely be happy to tackle `eth_getProof` if it's still a need! We have a hacky implementation that appears to be working correctly.

**Comment by davidmurdoch** [comment]
@kfichter I still haven't implemented it in the `next` branch yet, so please feel free. You'll want to put the rpc method somewhere around here: https://github.com/trufflesuite/ganache-core/blob/7ef14689fbdc8f4919a492fc7dceea3b78dcc84d/src/chains/ethereum/src/api.ts#L829

and tests would go here: https://github.com/trufflesuite/ganache-core/tree/next/src/chains/ethereum/tests/api/eth (you'd name the file `getProof.test.ts`).

To set up the repo, check out the `next` branch then read the [CONTRIBUING.md](https://github.com/trufflesuite/ganache-core/blob/next/CONTRIBUTING.md) to get started.

Let me know if you need any help!

**Comment by davidmurdoch** [comment]
Related issue: https://github.com/trufflesuite/ganache-core/issues/382
