### ISSUE TITLE
idea: add in warning to help switch over legacy instamine txs to new mode

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache-core#670]
When a request for a tx receipt comes in, and that tx's hash is still in the pending executables queue, log a warning to help devs understand why their code doesn't work.

credit: @cds-amal 

Note: there is a plan to make "legacyInstamine" mode the default mode in 3.0, and if that plan is implemented (meaning: nothing changes from 2.0 to 3.0), this warning won't be needed.

**Comment by eggplantzzz** [comment]
merged!
