### ISSUE TITLE
Error: Returned error: sender account not recognized

### ISSUE THREAD

**Issue by Madeindreams** [trufflesuite/ganache-core#678]
I unlock an account with ganache-cli Fork

ganache-cli --fork https://mainnet.infura.io/v3/MY_KEY_API -- unlock 0x6EBaF477F83E055589C1188bCC6DDCCD8C9B131a

When I deploy a contract with truffle it will see me as the first of the 10 accounts provided on start and they don't seem to be linked to that unlocked account.

In the truffle console I can see the balance of that account but it wont let me transfer?

So how do I use that unlocked account? Anything I do return

_Error: Returned error: sender account not recognized_

If that is not the right way to proceed how should I do it? If I use the fake account will i be able to spend the 100 eth on the fork mainet?

I'm running 

Ganache CLI v6.12.1
Truffle v5.1.48 (core: 5.1.48)
Solidity v0.5.16 (solc-js)
Node v10.17.0
Web3.js v1.2.1

**Comment by davidmurdoch** [comment]
If this is your actual command it would be because you have a space after between the dashes and `unlock`. `-- unlock 0x6EBaF477F83E055589C1188bCC6DDCCD8C9B131a` should be `--unlock 0x6EBaF477F83E055589C1188bCC6DDCCD8C9B131a`.

Once you have it work you should be able to just send a transaction `from: 0x6EBaF477F83E055589C1188bCC6DDCCD8C9B131a`.

**Comment by Madeindreams** [comment]
I was trying to use this address to make some transaction but i didn't need to. i just use the account 0 and it's working now.

**Comment by luziusmeisser** [comment]
Others googling this issue should note that the --unlock parameter does not check the validity of the provided address. I saw this error after providing a comma-separated list of addresses, i.e. "--unlock 0x123,0x234". Ganache accepts such clearly invalid inputs without complaining.

**Comment by codetit4n** [comment]
I had the same issue. What I found is that I was trying to unlock a contract address rather than an individual address. Just unlock non contract addresses and this will work.
