### ISSUE TITLE
Fork New Block While ganache-core is running

### ISSUE THREAD

**Issue by cwazy2020** [trufflesuite/ganache-core#686]
I would like to be able to fork a new block on a currently running instance of ganache-core.  Does anyone know if this is already possible, or if it could be added?

Alternatively, does anyone know how to properly dispose of an instance of ganache-core in node, while the script is still running? For example, how would I disconnect it from the upstream provider?

**Comment by gnidan** [comment]
Great idea, and with lots of tricky things to consider before this can be possible.

Regardless, closing this issue as duplicate of https://github.com/trufflesuite/ganache-core/issues/643

Thanks for your feedback!
