### ISSUE TITLE
Rename CLI options to align with provider/server options

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache-core#690]
The CLI has used snake-case (with inconsistencies) name styling for options where `@ganache/core` now consistently uses camel-case. For example, `chain.defaultBalance` instead of `default_balance_ether`

This issue changes the CLI options to be consistent with the provider/server options.

~@davidmurdoch do you want these to be back-compatible?~ This was answered on Zoom: yes

**Comment by mikeseese** [comment]
Resolved in #708
