### ISSUE TITLE
Ensure `@ganache/filecoin` mimics all stages of the storage mining process

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache-core#698]
Including funding, validating, acceptance, and sealing

**Comment by mikeseese** [comment]
This seems to be a bit more difficult to verify at the current time (`lotus-devnet` is out of date and is having issues currently). I could look at the old version that the network inspector shipped with, but I'd be verifying on a completely different version of the API

I'm going to defer this until later
