### ISSUE TITLE
Ensure `@ganache/filecoin` mimics all stages of the retrieval mining process

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache-core#699]

**Comment by mikeseese** [comment]
I'm not sure which parts of the retrieval deal are on the blockchain, but it seems that `Filecoin.ClientRetrieveWithEvents` gives a subscription/channel with `RetrievalEvent`s of the status of the retrieval: https://pkg.go.dev/github.com/filecoin-project/lotus@v1.4.0/markets/loggers#RetrievalEvent

I'm going to also defer this one a little until there's a more clear testing/validation strategy here
