### ISSUE TITLE
Issues embedding random data in the ethereum transactions data field

### ISSUE THREAD

**Issue by roderik** [trufflesuite/ganache-core#70]
I'm embedding a Merkle root in the data field of an ethereum transaction. this works fine for e.g. Parity.

On Ganache, however, I'm hit with this function that thinks I'm doing a contract call when I do a transaction that has a to and a data field. https://github.com/trufflesuite/ganache-core/blob/a48a99d2d5609f7e5a05c222fab8727b179c8f60/lib/statemanager.js#L811

```
        const sendTransaction = Promise.promisify(
          web3.eth.sendTransaction
        )
        const tx = await sendTransaction({
          to: address,
          from: address,
          data: merkleRoot,
        })
```

**Comment by davidmurdoch** [comment]
Thanks, @roderik! Closing this one as we'll be tracking this issue in #117.
