### ISSUE TITLE
Separate flavor packages into separate options packages

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache-core#700]
This issue rearchitects flavor implementations to be mini-monorepos to have "options" packages.

These options packages make it so that you can include the options packages without the actual core packages. This will help with future potential hot-loading of core packages

i.e.

```
/src
  /chains
    /ethereum
      /ethereum
        package.json
      /options
        package.json
    /filecoin
      /filecoin
        package.json
      /options
        package.json
```

**Comment by mikeseese** [comment]
Resolved in #703 and #709
