### ISSUE TITLE
ganache-core wouldn't build with node v14.15

### ISSUE THREAD

**Issue by bulgakovk** [trufflesuite/ganache-core#710]
## Expected Behavior
Installing `ganache-core` works

## Current Behavior

The package can't build

## Steps to Reproduce (for bugs)
You need `nvm` installed in order to follow these steps:
1. `nvm install 14.15`
2. `npm install ganache-core`

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): node `v14.15`, npm `v6.14.6`
* Operating System and version: MacOS Catalina 10.15.7

**Comment by davidmurdoch** [comment]
Just release a new version. Can you try again and let me know if this version works for you?

**Comment by bulgakovk** [comment]
Thanks for the quick response, it works 👍
