### ISSUE TITLE
Pin web3

### ISSUE THREAD

**Issue by sohkai** [trufflesuite/ganache-core#86]
## Current Behavior

It looks like web3 became unpinned with the [2.1.0 release](https://github.com/trufflesuite/ganache-core/commit/a0d38171b071e21ec9b13004e7023a554e8aaffa).

Unpinning web3 causes problems for dependents of ganache-core, since [web3 installs really oddly right now if it's not pinned](https://github.com/ethereum/web3.js/issues/966#issuecomment-372706361).

## Possible Solution

Go back to pinning it :).

## Your Environment
* Version used: 2.1.0
* Operating System and version: macOS 10.13.3
* Affected project: github.com/aragon/aragon-dev-cli

**Comment by alsco77** [comment]
I am having problems using ganache-core as a web3 provider. During builds, I am getting a load of errors with its dependents. I think it is what you are talking about. This was on 2.1.0, I have tried to use on 2.1.0-beta.7 and 1.1.2 and am still getting errors within the web3 node modules folder..

![screen shot 2018-03-18 at 13 37 31](https://user-images.githubusercontent.com/5690430/37562012-8f0e8c9c-2ab1-11e8-8122-98c6c2ac0ddd.png)

any ideas?

**Comment by seesemichaelj** [comment]
We now use `npm-shrinkwrap.json` as of `v2.1.6` which should pin all of versions.
